### ISSUE TITLE
safeMath for division overflow

### ISSUE THREAD

**Issue by ethers** [OpenZeppelin/zeppelin-solidity#115]
I think there's an edge case: INT_MIN/-1

**Comment by maraoz** [comment]
@ethers thanks for reporting, will investigate!

**Comment by adklempner** [comment]
Since we are using unsigned integers for all the functions in `SafeMath`, that edge case is not a concern.

Solidity already throws an error when trying to divide by 0 so I don't believe that there is a need for a safe division function.

**Comment by ethers** [comment]
Agree safe for all uint.  Keep in mind if signed ints functions are added.  Ideally Solidity will eventually throw on over/underflows so feel free to close.
