### ISSUE TITLE
Create a token with an owner

### ISSUE THREAD

**Issue by maraoz** [OpenZeppelin/zeppelin-solidity#120]
The idea is to have a token where the supply is controlled by an owner who can emit tokens and assign them. 
Probably should be a subclass of StandardToken and Ownable.

**Comment by federicobond** [comment]
Also, `recover(address)` or `expropriate(address)` functionality when keys are lost or stolen.

**Comment by DavidKnott** [comment]
I'm on it!

**Comment by miohtama** [comment]
Here is some prior art https://github.com/TokenMarketNet/ico/blob/master/contracts/MintableToken.sol

**Comment by maraoz** [comment]
@DavidKnott @miohtama awesome!

**Comment by tloriato** [comment]
Hey guys, I was wondering if I could get an overview over the `finishMinting()` function? I don't comprehend its purpose or why it should exists.

```
  /**
   * @dev Function to stop minting new tokens.
   * @return True if the operation was successful.
   */
  function finishMinting() onlyOwner returns (bool) {
    mintingFinished = true;
    MintFinished();
    return true;
  }
```
