### ISSUE TITLE
Adding contracts to Ethereum Package Repository

### ISSUE THREAD

**Issue by ice09** [OpenZeppelin/zeppelin-solidity#138]
Would be great to have your contracts added to the Ethereum Package Repository https://www.ethpm.com/ might increase adoption a lot.

**Comment by veox** [comment]
Relevant to EthPM are the [ERC190](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-190.md) packaging standard (currently draft status) and the [packaging specification](https://github.com/ethpm/ethpm-spec) linked from there.

**Comment by maraoz** [comment]
We already are in ethpm! https://medium.com/zeppelin-blog/zeppelin-now-supports-ethpm-95a1a6d561d3
