### ISSUE TITLE
Use 4 spaces instead of 2

### ISSUE THREAD

**Issue by LogvinovLeon** [OpenZeppelin/zeppelin-solidity#152]
Contribution guideline to this repo suggests using Solidity Style Guide https://github.com/ethereum/solidity/blob/develop/docs/style-guide.rst
It says, that one should use 4 spaces to indent.
All the contracts in this repo use 2 spaces. Probably we should change that?

**Comment by maraoz** [comment]
I personally don't agree with that style recommendation. What do other devs think? :+1: to agree, :-1: to disagree.

**Comment by maraoz** [comment]
closing after 7-1 voting result

**Comment by treeder** [comment]
Yes, I'm reviving a year old issue. 😉 

All the linters default to 4 spaces because that's the Solidity guidelines, I think it would be better for everyone if you guys got on board the 4 space train. http://solidity.readthedocs.io/en/v0.4.24/style-guide.html

**Comment by maraoz** [comment]
Strongly disagree :)

**Comment by maraoz** [comment]
But let's make a new vote. 

React with :+1: to vote for 2-spaces, react with :smile: to vote for 4-spaces

**Comment by treeder** [comment]
@maraoz based on what?  Just personal preference?  I like 2 spaces better too, but I also know that following community guidelines is better than my opinion.

**Comment by treeder** [comment]
This is what everyone sees by default when they use OZ contracts:

![screen shot 2018-08-10 at 9 41 00 am](https://user-images.githubusercontent.com/75826/43970173-8da0c090-9c81-11e8-8872-1dfd666f0755.png)

**Comment by elopio** [comment]
It's super easy to argue about code style. The solution to that is to follow the recommended practices of the language, and throw the discussion one level higher. So +1 to follow whatever the solidity devs recommend.

**Comment by treeder** [comment]
@nventuro give it a try! 😃   But in the meantime...

**Comment by shrugs** [comment]
4 spaces is just way too big, imo. I'd change the recommended value to 2 for the same reason everyone gave up on 4 spaces in javascript some time between 2014 and 2016.

**Comment by elopio** [comment]
@nventuro yup, this discussion should happen in the solidity repo, IMO.

**Comment by kabl** [comment]
I really don't care if it's two or four spaces. What I care is that when I download the tools and sources that they fit together without modification. - aka Interoperability.
