### ISSUE TITLE
Issuance event for StandardToken

### ISSUE THREAD

**Issue by miohtama** [OpenZeppelin/zeppelin-solidity#159]
Please see the discussion here:

https://github.com/ethereum/EIPs/issues/20#issuecomment-285449487

I have been working with several ERC-20 tokens in the past. It could make a token developer (not the creator, but wallets, exchanges and such) life simpler in many cases, if we could read the initial issuance of the tokens from the events themselves. 

I'd like to add an example of `IssuedToken` in OpenZeppelin. Before doing this, however, I'd like to hear comments what other people think.

**Comment by maraoz** [comment]
Is this like the `Mint` event of our `MintableToken` ?
see: https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/token/MintableToken.sol#L20

**Comment by tjayrush** [comment]
I fully support some sort of Issuance event being part of a standard. If one is trying to create some sort of automated auditing solution (as I am), it would be very useful. Of course, it won't force people to generate these events in their actual code, but having a defined event in the standard encourages people to write code that generates Mint or Issue events.

**Comment by maraoz** [comment]
+1, maybe this too should be part of a new crowdsale token standard?

**Comment by maraoz** [comment]
Closing because `MintableToken` already has a `Mint` and a `Transfer` event emitted when tokens are created.
