### ISSUE TITLE
Rename `Killable` and `kill`

### ISSUE THREAD

**Issue by Recmo** [OpenZeppelin/zeppelin-solidity#161]
The `SUICIDE` opcode has been renamed `SELFDESTRUCT` for reasons of sensitivity and morality. (We value human life more than contracts; etc.)

For the same reasons, a more appropriate name for `Killable` should be considered. `Destructable` is more in line with the new name of the opcode. `Terminable` is more in line with the traditional vocabulary around contracts.

See also https://ethereum.stackexchange.com/questions/9674/suicide-became-selfdestruct-kill-became-destroy-what-would-be-a-good-replaceme

**Comment by maraoz** [comment]
sounds good!
