### ISSUE TITLE
StandardToken conformity with ERC20

### ISSUE THREAD

**Issue by rmerom** [OpenZeppelin/zeppelin-solidity#163]
Re https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/token/StandardToken.sol 

The [standard](https://github.com/ethereum/EIPs/issues/20) maintains many of its methods need to return a `bool success`, e.g.
```
function transfer(address _to, uint256 _value) returns (bool success)
```

However, the current implementation of StandardToken throws instead of ever returning `false`.
While there is an ongoing debate on the standards page about return vs. throw, don't you think existing contracts should conform to the `return` paradigm for now?

**Comment by nickgeoca** [comment]
Removal of the return bool breaks our code, so we can no longer rely on zeppelin for ERC20. Also we concur that we should follow the standard until that standard has officially changed. Even if it makes more sense to remove the bool return.

**Comment by maraoz** [comment]
The standard is not final, it's a draft, and the discussion is ongoing. I know many projects using the `throw` version instead of returning `false`.
In any case, I just added a comment on the ERC20 discussion to push this forward: https://github.com/ethereum/EIPs/pull/610#issuecomment-300261622

**Comment by frangio** [comment]
I want to add the problem is more severe than I thought at first because someone that interacts with our token contracts assuming they conform to ERC20 as it stands today will see all functions returning boolean false even when they succeed.

I'm going to change this to return boolean values asap.

**Comment by frangio** [comment]
Standard compliance fixed. Our implementation still throws on error but this issue was closed because throwing is recommended by the standard, e.g.:
> The function SHOULD throw if the _from account balance has not enough tokens to spend.
