### ISSUE TITLE
TransferableToken lacks comments

### ISSUE THREAD

**Issue by miohtama** [OpenZeppelin/zeppelin-solidity#164]
`TransferableToken.sol` comes without any comments.

I'd suggest that the original authors communicate

* What is the intent of this contract

* How it should be used by developers

Generally, non-commented code is a bad practice and I'd suggest to maintain the current high standard of Zeppelin-Solidity some community guidelines would be in place to make this an exemplary project in this regard.

/cc @izqui

**Comment by izqui** [comment]
As referenced above, just did a PR explaining the purpose of Transferable Token. 

I have the feeling though that this should be in a separate documentation wiki or something like that, rather than directly in the source code. What do you think @maraoz @demibrener?

**Comment by demibrener** [comment]
Agree. We have a separate documentation on http://zeppelin-solidity.readthedocs.io/en/latest/. Here's the docs code: https://github.com/OpenZeppelin/zeppelin-solidity/tree/master/docs

Do you want to add the comments there?

**Comment by maraoz** [comment]
Closing as `TransferableToken` no longer exists
