### ISSUE TITLE
ERC20 approve problem

### ISSUE THREAD

**Issue by maraoz** [OpenZeppelin/zeppelin-solidity#168]
See https://drive.google.com/file/d/0ByMtMw2hul0EN3NCaVFHSFdxRzA/view

**Comment by izqui** [comment]
I like this simple approach to solving it 

https://github.com/Giveth/minime/blob/master/contracts/MiniMeToken.sol#L253

**Comment by frangio** [comment]
I like it too! It has the benefit that the token remains ERC20 compliant.
