### ISSUE TITLE
StandardToken.transferFrom potential security

### ISSUE THREAD

**Issue by miohtama** [OpenZeppelin/zeppelin-solidity#172]
I am reading this presentation:

<img width="708" alt="image" src="https://cloud.githubusercontent.com/assets/49922/24334169/68a0c180-126e-11e7-9e25-dedb819d28a0.png">

https://drive.google.com/file/d/0ByMtMw2hul0EN3NCaVFHSFdxRzA/view

It describes an attack vector against `transferFrom` and `allowance`. Looks like the current StandardToken implementation might be subject to attack. Before diving into deeper I'd like to ask

* Is this a real attack vector

* Should it be addressed

**Comment by maraoz** [comment]
yes: https://github.com/OpenZeppelin/zeppelin-solidity/issues/168

**Comment by maraoz** [comment]
Closing as duplicate
