### ISSUE TITLE
Change type of `owners` state variable from uint[] to address[] in `Shareable`

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/zeppelin-solidity#175]
In [Shareable.sol](https://github.com/OpenZeppelin/zeppelin-solidity/blob/b134645637b6169a1947a9caa1b92369310811f7/contracts/ownership/Shareable.sol#L26), the `owners` state variable is declared of type `uint[]`, but its members are actually of type `address`.

Besides the variable type, there are casts throughout the contract that should be removed.

**Comment by federicobond** [comment]
Confirmed. Want to send a PR updating the type and removing the casts?

**Comment by frangio** [comment]
Sure, I'll do it tomorrow.

**Comment by federicobond** [comment]
Awesome! Ping me if you need any help.
