### ISSUE TITLE
Rename `TransferableToken` to something more representative

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/zeppelin-solidity#179]
We have a contract named `TransferableToken`. Since a token is always "transferable" (the `transfer` method is part of ERC20), the contract name is confusing and doesn't explain its purpose.

The real functionality it provides is _limiting_ the amount of transferable tokens at a point in time.

How should we name it? I propose `LimitedTransferToken`.

**Comment by maraoz** [comment]
Good idea, thoughts @izqui ?

**Comment by izqui** [comment]
Makes total sense, I'm terrible at naming stuff sorry :P

**Comment by federicobond** [comment]
+1 to `LimitedTransferToken`

**Comment by maraoz** [comment]
@frangio +1 to `LimitedTransferToken` too. Want to implement it?

**Comment by frangio** [comment]
Ok, I'll send a PR.
