### ISSUE TITLE
Pausable token

### ISSUE THREAD

**Issue by maraoz** [OpenZeppelin/zeppelin-solidity#194]
Inspiration: https://github.com/BCAPtoken/BCAPToken/blob/5cb5e76338cc47343ba9268663a915337c8b268e/sol/BCAPToken.sol#L27

StandardToken + Pausable = PausableToken

**Comment by DavidKnott** [comment]
@maraoz I'll get that done today!

**Comment by maraoz** [comment]
@DavidKnott awesome! This will be a great addition to the framework :)
