### ISSUE TITLE
Allow Destructible to receive an optional address to which to send funds

### ISSUE THREAD

**Issue by maraoz** [OpenZeppelin/zeppelin-solidity#198]
Instead of sending always to `owner`

**Comment by misteraverin** [comment]
@maraoz Hi, I wanna work on this issue, but have question: in solidity we have no optional params to fucntions. Two ways to solve it: 
1. always add param to `destroy` function
2. make another contract `Destructible` with param
Which is more preferebly?

**Comment by maraoz** [comment]
@misteraverin thanks for taking this on. I think the best option is to add another method that receives a parameter, and leave the current one as is.
