### ISSUE TITLE
Recursive call attack to resetSpentToday in MultisigWallet

### ISSUE THREAD

**Issue by maraoz** [OpenZeppelin/zeppelin-solidity#200]
From the audit: 

`resetSpentToday` can be raced, allowing a double spend against the daily limit. So, someone pushes out a `resetSpentToday` call, and then any of the 'many' co-signers can race the call without recourse by transferring any amounts out of the contract so far left as spendable and then confirming. And of course anyone who has spending ability can spend while they wait for confirmations to come in.

You could make the `resetSpentToday` function take a current balance as an argument, that would reduce this problem to  'griefers might spend allowance in a race to break resetSpentToday', but once they did it, anyone authorized could spend out the daily balance, allowing a call of resetSpentToday(0) to work unilaterally.

**Comment by frangio** [comment]
Closed by #328.
