### ISSUE TITLE
Vault contract

### ISSUE THREAD

**Issue by maraoz** [OpenZeppelin/zeppelin-solidity#21]
The idea is to create a contract for fund management that is separate from other contract/business logic. In this way, we can define clear interfaces for dealing with funds and reduce the attack surface on contracts managing funds.

**Comment by maraoz** [comment]
Different fund management strategies can be defined, so we probably need a couple of different Vault contracts

**Comment by maurelian** [comment]
I was coming here to submit a suggestion for a "Deed contract", and I think Vault might be another word for the same idea?  

I got the idea from the ENS' initial registrar:
https://github.com/ethereum/ens/blob/master/HashRegistrarSimplified.sol#L25

The actual registrar contract [maps](https://github.com/ethereum/ens/blob/master/HashRegistrarSimplified.sol#L100) hashes to `entries`, and each [entry](https://github.com/ethereum/ens/blob/master/HashRegistrarSimplified.sol#L117) contains the deed's address, track's ownership, and other data relevant to the application. 

@maraoz I'm curious if you've seen this concept referenced or implemented elsewhere?

**Comment by maurelian** [comment]
https://medium.com/giveth/the-vault-contract-open-sourced-by-giveth-fe2261f7b91b#.grlu4c16c


https://github.com/Giveth/vaultcontract/blob/master/Vault.sol

**Comment by maraoz** [comment]
Here's an implementation by @Arachnid
https://gist.github.com/Arachnid/86f4d183c36f5b05e55b771034dffe1b

**Comment by ajsantander** [comment]
Deprecating in favor of #205
