### ISSUE TITLE
Make step-by-step contribution guide for developer

### ISSUE THREAD

**Issue by misteraverin** [OpenZeppelin/zeppelin-solidity#211]
Besides how to commit to repo, add info "how install environment and test code?".

**Comment by maraoz** [comment]
Agreed! This should be part of the README

**Comment by misteraverin** [comment]
@maraoz Look, I run `truffle test ./test/Destructible.js` and it says me:<br>
` Error: Cannot send value to non-payable constructor`. When i run `npm test` everything is ok. Do you know why?

**Comment by frangio** [comment]
@misteraverin It could be due to a difference in versions. npm runs its scripts using the locally installed versions of truffle and testrpc.

**Comment by misteraverin** [comment]
@frangio i updated truffle to latest version, error still exists.

**Comment by maraoz** [comment]
@misteraverin hmm... could you open a new issue for this please? Seems to be a different topic to your original request :)
