### ISSUE TITLE
Upgrade to truffle 3.2.2 and solidity 0.4.11

### ISSUE THREAD

**Issue by maraoz** [OpenZeppelin/zeppelin-solidity#215]

**Comment by frangio** [comment]
Keep in mind there's been a change to the exception raised by explicit `throw`s (ethereum/solidity#2260) so we'll have to change [a few things](https://github.com/OpenZeppelin/zeppelin-solidity/search?q=invalid+jump) in the tests.

**Comment by DavidKnott** [comment]
@frangio Thanks a lot for pointing this out! It helped a lot.

**Comment by frangio** [comment]
I'm glad! :-)
