### ISSUE TITLE
Add a refundable token

### ISSUE THREAD

**Issue by maraoz** [OpenZeppelin/zeppelin-solidity#217]
Make a token that can be refunded for ether given certain conditions (conditions should be defined in a function of the form `canRefund() returns bool` and be left abstract for the user to implement, similarly to how `Bounty` works)

**Comment by maraoz** [comment]
For example, `canRefund` could return true when a certain minimum amount of raised ether was not met

**Comment by frangio** [comment]
I think this was solved by `RefundableCrowdsale`. Feel free to reopen if there's an unaddressed usecase.
