### ISSUE TITLE
change all occurrences of uint for uint256

### ISSUE THREAD

**Issue by maraoz** [OpenZeppelin/zeppelin-solidity#226]
It's better to be explicit about types

**Comment by morrme** [comment]
i can help with this.

**Comment by maraoz** [comment]
@morrme nice, thanks!

**Comment by morrme** [comment]
@maraoz would you like the docstrings and other references changed as well, or just the declarations?

**Comment by maraoz** [comment]
Please change the docstrings too :)

**Comment by morrme** [comment]
this should be done by tomorrow--crazy week!

**Comment by rstormsf** [comment]
@maraoz https://github.com/OpenZeppelin/zeppelin-solidity/pull/269 here we go

**Comment by maraoz** [comment]
Reopening because @spalladino just found that `PausableToken` still has some references to `uint` instead of `uint256` (blame: @maraoz)

**Comment by maraoz** [comment]
See: https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/token/PausableToken.sol#L14

**Comment by BrianGuo** [comment]
@maraoz Just fixed this issue within my fork. I also changed uint to uint256 in most of the test files; if this isn't desired, i'll change it back promptly

**Comment by flockonus** [comment]
Hi guys, considering many ppl look up to OpenZeppelin contracts as reference, could you please list what are the tradeoffs to using `uint256` versus `uint`?

Also appreciated details to Struct, arrays and tight packing features.

**Comment by frangio** [comment]
Good suggestion @flockonus.

We think it's safest to be 100% explicit about types. Although `uint` is an alias for `uint256`, it makes the size implicit, for the only benefit of having a few characters less. There really isn't more to it than that. 🙂

They are aliases so they work exactly the same.

What is the question about structs and arrays?

**Comment by flockonus** [comment]
Your answer solve my question.

My other concerns are related to optimizing cost of storage, but i'll put it together in a separate question and drop by your Slack channel, thank you!

**Comment by rolandkofler** [comment]
The litmus test: would you file a issue for solidity to deprecate uint?
