### ISSUE TITLE
Add ECRecover lib

### ISSUE THREAD

**Issue by AugustoL** [OpenZeppelin/zeppelin-solidity#235]
I think it would be useful to have an ecrecover library, I been having trouble with the ecrecover method last week and I ended up using this https://gist.github.com/AugustoL/9ddf7996e23a01c6599323761c0deeef .

If you want I can add it to work like safeMath does.

**Comment by maraoz** [comment]
I like the idea! :D

**Comment by federicobond** [comment]
I haven't audited the code, but I like this too.

**Comment by AugustoL** [comment]
Thanks guys, I will do it soon.

**Comment by dob** [comment]
+1, was about to come here to make the same suggestion. Thanks @AugustoL
