### ISSUE TITLE
Comments switched in Pausable.sol

### ISSUE THREAD

**Issue by pdaian** [OpenZeppelin/zeppelin-solidity#244]
https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/lifecycle/Pausable.sol 

Comments are reversed on whenNotPaused and whenPaused.

**Comment by maraoz** [comment]
Good catch! :o

**Comment by maraoz** [comment]
fixed in https://github.com/OpenZeppelin/zeppelin-solidity/pull/428
