### ISSUE TITLE
Redundant state variable in MintableToken

### ISSUE THREAD

**Issue by mezrin** [OpenZeppelin/zeppelin-solidity#245]
Looks like a redundant variable. Parent contract already has this.
We just need to delete this line

https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/token/MintableToken.sol#L21

**Comment by maraoz** [comment]
+1! Want to issue a PR?

**Comment by DavidKnott** [comment]
@maraoz I'll do this one as well
