### ISSUE TITLE
Implement "A Secure way to make a send in ethereum" by @jbaylina

### ISSUE THREAD

**Issue by maraoz** [OpenZeppelin/zeppelin-solidity#246]
See https://www.reddit.com/r/ethdev/comments/6ekz2j/a_secure_way_to_make_a_send_in_ethereum/

**Comment by rstormsf** [comment]
should we replace every single `send()` with `secureSend()`?

**Comment by federicobond** [comment]
I have known about this technique for a while, and I still think it's way too hacky to become the standard way to implement secure send. We should treat it as a forceSend rather than secureSend, and use it only in very limited scenarios.

**Comment by federicobond** [comment]
Let me be more clear: I think contracts should be able to reject payments if they cannot handle them or are unwilling to handle them. Every contract that sends value should be able to handle that condition gracefully. Also, contracts should be allowed to at least log an event when they receive value, as a courtesy payed by the originator of the transaction (as the current semantics of send allow).

**Comment by frangio** [comment]
I agree with @federicobond. Solidity `send` and `transfer` are secure enough. Particularly `transfer`, which should be the standard secure send.

Should we add `forceSend` to OpenZeppelin? I think it's an interesting experiment, but it probably should be used in practice.

**Comment by federicobond** [comment]
Is there a concrete use case that requires forceSend? Otherwise I think it would promote bad practices among Solidity developers.

**Comment by maraoz** [comment]
Agreed. I regret opening this issue now :P
