### ISSUE TITLE
Should Ownable be called Controllable? 

### ISSUE THREAD

**Issue by maraoz** [OpenZeppelin/zeppelin-solidity#247]
Idea from: https://github.com/status-im/status-network-token/blob/2152b17aa2ef584a2aea95533c707a345c6ccf69/contracts/MiniMeToken.sol#L54

**Comment by federicobond** [comment]
I like Ownable. Controllable sounds more like a category of which Ownable is part of. In other words, having an owner is one of the many ways a contract can be "controlled". Another way would be to have the approval of a majority of stakeholders or any other governance model.

**Comment by federicobond** [comment]
But I see the confusion it can cause between the owner of the contract itself and the owners of tokens managed by that contract.

**Comment by frangio** [comment]
I like Ownable too. Aside from not being the only way a contract can be controlled, the owner doesn't necessarily _control_ the contract as much as the word can imply.
