### ISSUE TITLE
Prevent common transfer mistakes in StandardToken

### ISSUE THREAD

**Issue by maraoz** [OpenZeppelin/zeppelin-solidity#248]
Maybe we should add checks to prevent:

- sending to `0x0` address
- sending to self (the token contract)

See: https://github.com/status-im/status-network-token/blob/2152b17aa2ef584a2aea95533c707a345c6ccf69/contracts/MiniMeToken.sol#L214

**Comment by GNSPS** [comment]
Why do you think this would be beneficial @maraoz ?

I tend to dislike deviations from standard ERC20 functions gas costs. Do you think those edge cases justify the sum of every agent losing a bit more gas in every transaction?

(Genuinely interested in getting everyone's opinion, these are not rhetorical questions 😄 )

**Comment by maraoz** [comment]
Agree with your gas concerns @GNSPS. 
The design direction we're taking is making `StandardToken` super secure and gas-intensive, and later we want to add a gas-optimized version with less security precautions.

**Comment by maraoz** [comment]
I just realized the phrase "Agree with your gas concerns" can be very funny if taken out of context ^^

**Comment by GNSPS** [comment]
Laughed hard! 😂

**Comment by MaxDinman** [comment]
Actually it depends on the case, sometimes it makes sense to spend ~8k gas for the above checks, however the `StandardToken` is definitely not the case.

**Comment by frangio** [comment]
Just for the record, a single `require` of a comparison between a state variable and a constant costs about 60 gas.

**Comment by spalladino** [comment]
@maraoz we have been reviewing this issue, and while I agree on preventing sends to `0x0`, I can think of some scenarios where the StandardToken is extended with additional functionality and is expected to hold some of its own tokens. WDYT about adding that restriction into a `SaferToken` (see https://github.com/OpenZeppelin/zeppelin-solidity/pull/447/), instead of on the Standard Token?

**Comment by maraoz** [comment]
+1
