### ISSUE TITLE
Consider replacing our MultisigWallet with Stefan George's version

### ISSUE THREAD

**Issue by maraoz** [OpenZeppelin/zeppelin-solidity#251]
See this beauty: https://github.com/status-im/status-network-token/blob/master/contracts/MultiSigWallet.sol

**Comment by frangio** [comment]
The actual repository is [ConsenSys/MultiSigWallet](https://github.com/ConsenSys/MultiSigWallet).

Notice that it also provides a GUI to manage the wallet.

The implementation is really good. Should we include it as part of OpenZeppelin or just link to the ConsenSys repository?
