### ISSUE TITLE
Remove npm install script that copies Zeppelin contracts to contract/ folder

### ISSUE THREAD

**Issue by maraoz** [OpenZeppelin/zeppelin-solidity#253]
Not needed anymore, as latest truffle supports `npm` integration

**Comment by rstormsf** [comment]
Looks like current `package.json` doesn't have any `post-install`. Am I right?

**Comment by maraoz** [comment]
I meant "install", sorry

**Comment by rstormsf** [comment]
@maraoz https://github.com/OpenZeppelin/zeppelin-solidity/pull/272 done

**Comment by rstormsf** [comment]
@maraoz - would love if it can be updated in npmjs registry, cause it creates zeppelin folder every time we do `yarn add zeppelin-solidity`

**Comment by maraoz** [comment]
We're planning on releasing a new minor version next week after merging some of the pending PRs :)
