### ISSUE TITLE
Merkle proof library

### ISSUE THREAD

**Issue by yondonfu** [OpenZeppelin/zeppelin-solidity#254]
It seems like it would be useful to have a standard on-chain library for verifying Merkle proofs since they offer a compact way to prove the existence of some element in a set given a past commitment of a Merkle root.

This contract seems like a great start and contains functions that verify a Merkle proof both in the case where pairs of elements are sorted and the case where the order of elements is preserved: https://github.com/ameensol/merkle-tree-solidity/blob/master/src/MerkleProof.sol

Happy to get started with porting this functionality to a library and add tests if there is interest!

**Comment by DavidKnott** [comment]
@yondonfu I'd be interested collaborating on this!

**Comment by yondonfu** [comment]
@DavidKnott Awesome, I'll be submitting a PR later today and it'll definitely be helpful to get people to go over the implementation.

**Comment by frangio** [comment]
Added in #260.
