### ISSUE TITLE
Remove short address attack checks from tokens

### ISSUE THREAD

**Issue by maraoz** [OpenZeppelin/zeppelin-solidity#261]
If `transfer` and `transferFrom` are used by a subcontract's function with less arguments, the checks will fail.

**Comment by maraoz** [comment]
@izqui thoughts? This happened to me recently and had to use a horrible workaround

**Comment by federicobond** [comment]
+1 to removing it. An honorable effort, indeed, but it was done at the wrong layer and in response to a single isolated case of very poor validation in the upper layers.

**Comment by izqui** [comment]
I agree. I haven't even deployed this in our own token.

**Comment by DavidKnott** [comment]
@federicobond Just trying to learn, what layer do you think short address attack protection should be built into?

**Comment by federicobond** [comment]
It should be handled by the libraries that read the contract ABI and let you create transaction payloads out of it (web3.js, truffle-artifactor, etc.)

**Comment by federicobond** [comment]
Think of this analogy: dynamically-loaded libraries should not (and probably cannot) verify that you have pushed the right arguments into the stack before calling them. They just expose their ABI as header files and (unless you are writing assembly by hand) any high-level language compiler worth its salt will take care of the rest. What the library code SHOULD do is try to make sense of the arguments assuming they were pushed the right way, or bail out if not.

**Comment by frangio** [comment]
I'd like to add too that the modifier is incredibly error prone because the `size` argument has to be calculated and kept up-to-date by the programmer.

**Comment by frangio** [comment]
Here's a demo of the error @maraoz mentions:
https://ethereum.github.io/browser-solidity/#gist=f5c444b9e087d03438aa990cb91b9e3a

**Comment by rpsnoopy** [comment]
How can you prevent malicious user to send the short address to your contract if the error is trapped at the useri interface level only? The user interface is out of control for any public function: you can write your own and call whatever.

Put it in using >= in the check

**Comment by frangio** [comment]
Web3.js correctly handles this. I don't remember right now if it pads an address argument to its full length, or it just rejects a short one. This was never a problem with web3.js. The attack was done on a website which used its own handwritten transaction encoder.

**Comment by elopio** [comment]
For the record, Solidity 0.5.0: https://github.com/ethereum/solidity/pull/4224
