### ISSUE TITLE
ERC20 interface does not match actual ERC20

### ISSUE THREAD

**Issue by interfect** [OpenZeppelin/zeppelin-solidity#270]
Specifically, the `transfer` (from `ERC20Basic`) and `transferFrom` functions do not return bools.

While whether the OpenZeppelin ERC20 token *implementations* should throw on failed transfers or not is an open question (see #163), the *interfaces* need to support the return value, because other ERC20 implementations (like [this one](https://github.com/Firstbloodio/token/blob/master/smart_contract/FirstBloodToken.sol)) are going to use it. Otherwise, there's no way to take an arbitrary ERC20 token and make transfers and know if the transfers went through.

**Comment by frangio** [comment]
Hi @interfect! Thank you for contributing.

We're holding this issue and #163 open because the ERC20 standard is still a draft. I share your concerns about interoperability, though. We will look into it.

**Comment by interfect** [comment]
This issue has now come back to bite me, many years later.

I deployed a live token with the original, non-returning OZ implementations from then-current OZ v1.0.7. Then I upgraded the project to newer OZ which provided the return, and wrote more code against OZ's current `IERC20` interface that was supposed to talk to the original contract.

For a long time, expecting a return value from an ERC20 contract call that didn't provide one didn't cause any problems; the return value would register as true in the calling contract. I had a test for this in my codebase, which I eventually removed after many months of it working correctly. (Maybe it didn't always do this for all token implementations, or for all caller's stack states? #308 implies that calls to functions without return values had been observed registering as a false return value to the caller.)

But eventually something changed. With solc v0.6.10, on the current EVM, trying to call an OZ v1.0.7 ERC20 with e.g. OZ 3.0.2's IERC20 does not work for e.g. `transferFrom`. The Truffle debugger shows something like this:

```
Stacktrace:
Error: Improper return (may be an unexpected self-destruct)
  at unknown function [address 0xAB6CF87a50F17d7F5E1FEaf81B6fE9FfBe8EBF84] (/z/home/anovak/workspace/macroverse/contracts/MacroverseUniversalRegistry.sol:518:17)
  at MacroverseUniversalRegistry.commit [address 0x79c529ce41E4C070dB1f56eab4743bc04495EF2d] (/z/home/anovak/workspace/macroverse/contracts/MacroverseUniversalRegistry.sol:518:17)
  at MacroverseUniversalRegistry [address 0x79c529ce41E4C070dB1f56eab4743bc04495EF2d] (/z/home/anovak/workspace/macroverse/contracts/MacroverseUniversalRegistry.sol:507:5)

Location of error:

MacroverseUniversalRegistry.sol:

516: 
517:         // Make sure we can take the deposit
518:         require(depositTokenContract.transferFrom(msg.sender, address(this), deposit), "Deposit not approved");
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                          
```

Does OZ have a recommended workaround for calling into tokens that may be these old ERC20s safely on newer OZ/solc/EVM? Some kind of assembly block that will make the call but ignore the return value that may or may not be there? Or do you have to just know if any given token is the old kind in advance, and write your own `IOldBrokenERC20` to call it through?

**Comment by frangio** [comment]
@interfect Yes, take a look at [`SafeERC20`](https://docs.openzeppelin.com/contracts/3.x/api/token/erc20#SafeERC20). Apologies that this library is not very well documented at the moment but it should be simple to use.

**Comment by interfect** [comment]
Oh, this looks to be exactly what I need. Thank you!

**Comment by frangio** [comment]
Here's a comment I posted in the forum about it. https://forum.openzeppelin.com/t/safeerc20-tokentimelock-wrappers/396/2
