### ISSUE TITLE
Redundant lockfiles (npm and yarn)

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/zeppelin-solidity#284]
~There's already a `yarn.lock` file in the repository. It's not clear if we should also add npm5's `package-lock.json`.~

See update [below](https://github.com/OpenZeppelin/zeppelin-solidity/issues/284#issuecomment-322009726).

**Comment by frangio** [comment]
Keeping an eye on yarnpkg/yarn#3614. We're not the only ones confused by this. 🙂

**Comment by frangio** [comment]
There are now both `yarn.lock` and `package-lock.json` files in the repository. They are kept in sync via `yarn import` after #363.

**Comment by Shrugs** [comment]
We should probably pick one and enforce its usage. I'm pretty ambivalent about which one the project chooses, but having both seems unnecessary. I can put out a PR for this later if we've made a decision.

**Comment by frangio** [comment]
Currently yarn is used in Travis, but most of us use npm locally. Travis was set up to use yarn in #250 because of performance reasons.

I'd be in favor of moving to npm completely and removing `yarn.lock`, now that npm 5 is more performant.
