### ISSUE TITLE
Remove msg.sender == beneficiary requirement from TokenTimelock#claim()

### ISSUE THREAD

**Issue by maraoz** [OpenZeppelin/zeppelin-solidity#293]
This makes the timelock usable from "dumb" beneficiaries. 

Currently, only beneficiaries that are able to call the `claim` method are supported. If we remove the check, any other address can release the tokens. 

See: https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/token/TokenTimelock.sol#L34
Ping @frangio

**Comment by frangio** [comment]
+1
Maybe we should rename `claim` to `release`, then.

**Comment by maraoz** [comment]
+1 to renaming
