### ISSUE TITLE
Separate example contracts from "functionality" contracts

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/zeppelin-solidity#295]
We should provide examples of usage of our contracts. I think at the moment the only example is SimpleToken. However, it's placed right next to the contracts that provide token functionality and is not easy to find or distinguish.

We should create a special directory for examples, and add new ones. We need a complete example for Crowdsale, for example.

**Comment by maraoz** [comment]
Agreed. We should have an examples folder
