### ISSUE TITLE
Contactable contracts

### ISSUE THREAD

**Issue by maraoz** [OpenZeppelin/zeppelin-solidity#3]
See "Contact" section in http://vessenes.com/we-need-some-best-practices-for-smart-contracts/

**Comment by JGcarv** [comment]
Hi @maraoz ! I would like to do this one. But I have some questions.

What would be the ideal type of a contact information? (A string? A byte array? Some kind of form-like struct?)

I've made a sketch of what I have in mind:
```
pragma solidity ^0.4.0;
import './Ownable.sol';

contract Contactable is Ownable{

     string public contactInformation;    

     function setContactInformation(string info) onlyOwner{
         contactInformation = info;    
     }

}
```

What do you think? Any other functionality comes to mind?

Thanks!

**Comment by maraoz** [comment]
@JGcarv looks good! Thanks for your contribution :)

Feel free to [open a pull request](https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/CONTRIBUTING.md#pull-request-workflow) with it.

**Comment by maraoz** [comment]
Thanks @JGcarv for tackling this one! :)

**Comment by facuspagnuolo** [comment]
This feature is already implemented. Closing.
