### ISSUE TITLE
FinalizableCrowdsale is not trustless

### ISSUE THREAD

**Issue by adamdossa** [OpenZeppelin/zeppelin-solidity#301]
Hey,
I noticed that the call to `finalize()` in FinalizableCrowdsale.sol is guarded by the modifier `onlyOwner`.
Unless this finalizable action is meant to be optional, I can't really see any reason for it not to be open to the public to call to avoid the owner being able to block the token contracts state from progressing if needed.
For example, in the derived RefundableCrowdsale.sol crowdsale contributors can't process their refunds until the crowdsale has been finalized, which only the owner could do - hence the owner could block refunds (note - they would also block themselves from collecting the wallet ether).
Thoughts? Happy to submit a PR if consensus is that this should be changed.
Thanks,
Adam

**Comment by frangio** [comment]
It is usually for security reasons that we only allow an owner to trigger these administrative tasks, so that an attacker cannot use the function.

That said, I see how it can be an issue. It would be ok if the owner was incentivized to call `finalize`, but in `RefundableCrowdsale`, for example, they are only incentivized when the crowdsale was successful, and there is not much incentive to give people their refunds.

I'd like to hear what others think about this too.

**Comment by federicobond** [comment]
In a way, the whole Crowdsale thing relies on trusting that the token emitter is going to follow up with their plans to build a strong network around them, so I'd argue that this is a minor detail compared to the rest.

In this particular case, though, the problem with letting anyone call `finalize` is that it will prevent any further minting of new tokens, which the owner might want to do right after the sale to ensure that the team and early contributors get their agreed upon shares.

**Comment by adamdossa** [comment]
I def. see your point, but a couple of other observations:
1) in the above, any action the owner may want to take after the sale finishes should be a part of the finalize function I think - the function doesn't take arguments so would need to encode all of the logic upfront but this doesn't seem unreasonable to maintain a trustless nature.
2) if finalize needs to remain as callable only by the owner I wonder whether the refundable crowdsale contract should be implemented outside of the finalizable framework so that refunds can remain trustless (so be based purely on whether a crowdsale has completed, and if so whether or not it met its stated goal).

**Comment by frangio** [comment]
I agree with your first point. A trustless crowdsale should encode all necessary actions (such as further minting) in the crowdsale finalization. In that case, I think anyone should be able to trigger it.

A derived contract can always add extra requirements to an inherited function. A specific crowdsale would be able to restrict finalizing to an owner by subclassing Crowdsale and adding a check, if so desired.

I'd like to reiterate two points though.
1. Allowing anyone to trigger finalization enlarges the attack surface of the contract.
2. Full trustlessness is impossible. We aim for trust minimization.

Whatever path we choose it's important that it be very well communicated. I'll think about it a bit more. What would you guys think about providing the less restrictive option (anyone can finalize) by default?

**Comment by jakub-wojciechowski** [comment]
I think having a trustless finalization by default it's a good idea. 

@frangio do you have in mind any example of an attack on triggering finalization while is well guarded by invariants check or are you referring to the case that some developers may specify this checks badly?

**Comment by maraoz** [comment]
Closing this as it's a design decision we took. A trust-reduced version could be proposed too, but I don't think we should change the existing implementation.

For more on our rationale, see: https://docs.google.com/presentation/d/1_SiLRCTpypJvsyjgOMWgOQahTrUDexuWJQQNHEvC2A0/edit#slide=id.g282810e2b6_0_42

**Comment by medvedev1088** [comment]
As I understood from the rationale, the reason not to make it trustless is because making changes to the code can potentially make it less secure.

**Comment by Shrugs** [comment]
just throwing it out there: various audit reports I've seen include this complaint as well. I still support keeping this as-is, but it's something to note.

**Comment by adamdossa** [comment]
Yep - I've also been asked to modify this contract to a "trustless" version by a few clients. On the presentation linked above, I didn't find the motivation very convincing - it would be straightforward to make the finalize function only callable once if needed. Having said that, in any crowdsale you have to trust the intentions of the issuer largely anyway (otherwise the tokens would be worthless) so not sure how important this is.
