### ISSUE TITLE
Add continuous token sale contract

### ISSUE THREAD

**Issue by federicobond** [OpenZeppelin/zeppelin-solidity#303]

**Comment by jakub-wojciechowski** [comment]
Isn't the continuous crowdsale a more basic version of a crowdsale without `_startBlock`, `_endBlock` and `cap` or do you @federicobond  have a different idea like multiple rounds (preSale, round1, roud2...)?

**Comment by federicobond** [comment]
They can share some logic, you are right. I was thinking more about the issuance model for continuous sales though (fixed amount per block, per time frame, etc.)

**Comment by jakub-wojciechowski** [comment]
I see your point. I think we can achieve by a customizable Cap Strategy. Currently, we have a single Cap but it may be defined per block or time period. What's your view on that?

BTW, I've just looked at the CappedCrowdsale and realised that we require the last transaction to precisely hit the capped target. It can bring a lot of frustration to users burning gas by trying to put the final transaction. The common behaviour is to return part of the donation that is above the cap as soon as it's exceeded. Should we create an issue and fix this?

**Comment by frangio** [comment]
@jakub-wojciechowski Let's stay on-topic and discuss only continuous crowdsales here. 🙂 We can talk about the "precise cap" problem in a different issue. (I'm not sure we want to implement the partial refund.)

We should be careful not to conflate the different kinds of limits a crowdsale can have. "Continuous" refers to the lack of a limit in the crowdsale's _running time_. "Capped", OTOH, refers to the limit in the amount of _money_ that can be raised.

I'm not sure I understand how the issuance model should be part of the logic of a ContinuousCrowdsale contract. Would it make sense to not restrict issuance in any way, and let that happen elsewhere?

**Comment by jakub-wojciechowski** [comment]
Yes, you are right lets move "precise cap" to a different issue. 

I agree, let's separate time boundaries and issuance model and decide what to do with the first problem.

If we stick to the inheritance model, continuous crowdsale seems to be a parent to a current `Crowdsale` as it is more generic by not imposing any limitation for `startBlock` and `endBlock`. I see the refactor as extracing all logic that handles time boundaries to a sublass 'FixedCrowdsale' and our base `Crowdsale` will automatically become a continuous one.

**Comment by keith24** [comment]
Since Crowdsale's endTime is uint256, can't I just max it out?  
```solidity
function ContinuousCrowdsale(uint256 _startTime, uint256 _rate, address _wallet) {
  uint256 max = 2**256 - 1; // https://ethereum.stackexchange.com/a/7294/1562
  Crowdsale(_startTime, max, _rate, _wallet);
}
```

**Comment by ajsantander** [comment]
Please see the crowdsale refactor #744.
Instead of making a more abstract FixedCrowdsale with no time boundaries, we removed time boundaries from Crowdsale and implemented them in a more specific TimedCrowdsale.
