### ISSUE TITLE
MintableToken return values

### ISSUE THREAD

**Issue by jakub-wojciechowski** [OpenZeppelin/zeppelin-solidity#306]
Currently, both functions have return values in their signatures:

```
function mint(address _to, uint256 _amount) onlyOwner canMint returns (bool) {
function finishMinting() onlyOwner returns (bool) {
```

which is inconsistent with the general approach used in this repo to prefer fail-fast error handling with throwing. Moreover, the comment suggests:

`* @return A boolean that indicates if the operation was successful.`

that the operation may return false which is never the case.

Maybe it's better to strip this return values or is there any reasoning behind them that I'm missing?

**Comment by frangio** [comment]
We want to make this consistent, but it's still undecided whether we'll keep return values or not.

Issues #163 and #270 are open until this is decided, and when that goes through we'll update all token contracts to be consistent.

**Comment by jakub-wojciechowski** [comment]
Thx for the answer @frangio !
Both of the issues refer to [ERC-20](https://github.com/ethereum/EIPs/issues/20) interface and the mentioned functions are out of the scope of the reference so it won't break any compatibility requirements. Moreover, the main argument for return values is to save gas costs for users by returning `false` while the methods never return `false` but throw exception consuming all of the gas. In other words, the current implementation neither follows return pattern by being able to return `false` nor have a simple signature without return values.
Please, let me know if you see my point in here?

**Comment by frangio** [comment]
I do see your point! I understand this isn't about ERC20 compatibility, but consistency within the OpenZeppelin framework.

It's also true that the return values are basically unused because methods throw on error. This is actually similar to what is suggested in ERC20, for example in the description of `transfer`:
> The function SHOULD throw if the `_from` account balance has not enough tokens to spend.
It's odd behavior, yes...

In any case, we're going to add back return values to our ERC20 tokens, so MintableToken will keep them in the spirit of consistency.

Thanks for bringing this up @jakub-wojciechowski!

**Comment by jakub-wojciechowski** [comment]
Should I make a small PR to return false when it cannotMint, so it will make sense to check if `mint` reported a successful or unsuccessful execution? LMK what do you think @frangio?

**Comment by frangio** [comment]
#308 fixes ERC20 compliance by adding back all the return values. This means we're keeping MintableToken's return values as well.

I'd actually prefer to keep the current throwing behavior too. We believe this protects against errors, and it's consistent with ERC20 so it should be ok.

It is also consistent with the rest of OpenZeppelin. We might revisit this in the future, though.
