### ISSUE TITLE
Inconsistent behaviour in VestedToken.sol

### ISSUE THREAD

**Issue by adamdossa** [OpenZeppelin/zeppelin-solidity#307]
Hi All,

My reading of the `transferableTokens` function in VestedToken (which inherits from LimitedTransferToken) is that it is a little inconsistent.

For addresses which have vesting grants, the logic works correctly, specifying that such addresses can transfer a minimum of their vested tokens and and other restrictions that may exist (through the use of `super.transferableTokens`).

However, for addresses which don't have vesting grants, the function just returns:  
`balanceOf(holder)`.

My suggestion is that for non-grant holder addresses, the logic should be:  
`if (grantIndex == 0) return Math.min256(balanceOf(holder), super.transferableTokens(holder, time));`
rather than
`if (grantIndex == 0) return balanceOf(holder);`

This would be more consistent with the design pattern of LimitedTransferToken, as documented in its comment:
```
* LimitedTransferToken has been designed to allow for different limiting factors,
 * this can be achieved by recursively calling super.transferableTokens() until the base class is 
 * hit. For example:
 *     function transferableTokens(address holder, uint64 time) constant public returns (uint256) {
 *       return min256(unlockedTokens, super.transferableTokens(holder, time));
 *     }
 ```

Thoughts? It would be a simple PR which I can put in if there is consensus.

Thanks,
Adam

**Comment by jakub-wojciechowski** [comment]
Hi Adam, 
Well-spotted issue. Isn't it that:

`super.transferableTokens(holder, time) <= balaceOf(holder)`

Maybe it's better to check this invariant in LimitedTransferToken, but I'm not sure if it's much needed as it's going to be checked finally by SafeMath constraints in:
`balances[_from] = balances[_from].sub(_value);`

**Comment by adamdossa** [comment]
Hmm - not sure that is exactly the issue I mean.

The issue I'm flagging is that there is a `transferableTokens` function should always return the minimum of what it considers to be the transferable amount of tokens, and `super. transferableTokens`.

VestedToken does this if the account is a grant holder, but doesn't do this if it isn't.

So the line:
`if (grantIndex == 0) return balanceOf(holder);`
should be replaced by
`if (grantIndex == 0) return Math.min256(balanceOf(holder), super.transferableTokens(holder, time));`

This is not to ensure that the amount returned is <= balanceOf(holder), it's more to ensure that any other LimitedTokenTransfer contracts in the inheritance hierarchy are respected.

**Comment by jakub-wojciechowski** [comment]
In other words, I was just asking if returning only: 

`return super.transferableTokens(holder, time)`

instead of `min()` will be sufficient?

**Comment by adamdossa** [comment]
Ah I see - you're right that would be an option if you assume that someone else will make the check - I think it is probably clearer to take a min. anyway and will always be safe (but have a small gas cost I guess).

**Comment by jakub-wojciechowski** [comment]
Cool, finally we've reached an accord!
My view is that a subclass shouldn't validate the correctness of a super class. 
It's a small suggestion, just to make your great update even a slightly better and more efficient :)
