### ISSUE TITLE
Off-by-one error in VestedToken.sol

### ISSUE THREAD

**Issue by cintixverum** [OpenZeppelin/zeppelin-solidity#309]
Line 52: `if (tokenGrantsCount(_to) > MAX_GRANTS_PER_ADDRESS) throw;` should use `>=` instead of `>`.

**Comment by frangio** [comment]
This doesn't look like an error to me, it just means the maximum is inclusive.

@maraoz @izqui Please confirm.

**Comment by cintixverum** [comment]
You can't say there's a maximum of 20 grants, then allow 21.  "The maximum is inclusive" is some of the most impressive mental gymnastics I've ever seen.  It's either a simple off-by-one error or the worst naming convention in human history.  I'm in awe that you would prefer the latter.

**Comment by frangio** [comment]
We prefer a more civil tone around here, @cintixverum. Understand it's not my intention to perform any mental gimnastics here, and that you can point things out in a kinder way.
