### ISSUE TITLE
Possible bug in StandardToken.sol

### ISSUE THREAD

**Issue by abbasmhd** [OpenZeppelin/zeppelin-solidity#313]
in your **StandardToken.sol** there is a comment says

    // Check is not needed because sub(_allowance, _value) will already throw if this condition is not met
    // if (_value > _allowance) throw;
    balances[_to] = balances[_to].add(_value);
    balances[_from] = balances[_from].sub(_value);
    allowed[_from][msg.sender] = _allowance.sub(_value);

 is that mean if ` balances[_from] = balances[_from].sub(_value);` throw an error `balances[_to] = balances[_to].add(_value);` is executed regardless???
in that case i would move all the `sub` before the `add` 

    balances[_from] = balances[_from].sub(_value);
    allowed[_from][msg.sender] = _allowance.sub(_value);
    balances[_to] = balances[_to].add(_value);

https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/token/StandardToken.sol#L29-L35

**Comment by frangio** [comment]
Hi @abbasmhd, thanks for reporting. :smiley:

In Ethereum, `throw` rolls back all the state changes made in a transaction. So, if the `sub` fails, the `add` is undone.
