### ISSUE TITLE
Ownable transferOwnership() silently fails

### ISSUE THREAD

**Issue by pooleja** [OpenZeppelin/zeppelin-solidity#319]
Is there a reason that transferOwnership() doesn't throw an error if the address is 0?  I think silently failing could cause users/contracts to think that the ownership transfer succeeded even though they messed something up.  This could lead to further problems.

```
  function transferOwnership(address newOwner) onlyOwner {
    if (newOwner != address(0)) {
      owner = newOwner;
    }
  }
```

**Comment by frangio** [comment]
Thanks for reporting @pooleja! There's no reason, it should be fixed. Do you want to submit a PR?

**Comment by pooleja** [comment]
Incoming ;)
