### ISSUE TITLE
yarn test returns 0 in CI even when tests fail.

### ISSUE THREAD

**Issue by cgewecke** [OpenZeppelin/zeppelin-solidity#322]
See [build 433](https://travis-ci.org/OpenZeppelin/zeppelin-solidity/builds/253602206).

**Comment by maraoz** [comment]
Damn, good catch! Any ideas on how to fix this?

**Comment by cgewecke** [comment]
It almost never happens, that was an rare case. Unfortunately my bash skills are non-existent. How do you capture the result of command and exit with it? I think the problem is that the testrpc shutdown always succeeds no matter what happens and that's the 'result'.

**Comment by frangio** [comment]
That's correct @cgewecke. I'm going to fix this.
