### ISSUE TITLE
Add burnable token

### ISSUE THREAD

**Issue by maraoz** [OpenZeppelin/zeppelin-solidity#324]
Inspiration: https://github.com/decentraland/mana/blob/master/contracts/BurnableToken.sol

**Comment by pash7ka** [comment]
Do we want to allow BurnableTokens to be burned if sended to 0 address?
Also, may be it is useful to burn tokens sended to the token address. This'll allow simple burning tokens from any wallet which supports ERC20.
Also, may be it is usefull to allow token holders to be rewarded for burning. So we may end up with smth like this: https://github.com/MATREXA/MTRX-Contract/blob/master/BurnableToken.sol

**Comment by frangio** [comment]
I think we should keep the semantics of `transfer` as they are. I wouldn't expect a token to be burnable through a standard ERC20 wallet.

The reward mechanism is interesting! Quite rare, though. I don't think most tokens will find use in something like it.

Closing since it was fixed by #341!
