### ISSUE TITLE
Add complex crowdsale example

### ISSUE THREAD

**Issue by maraoz** [OpenZeppelin/zeppelin-solidity#331]
Add an example contract that inherits from `CappedCrowdsale`, `FinalizableCrowdsale`, `RefundableCrowdsale` as documentation on how to do it.

**Comment by frangio** [comment]
See #295 as well.

**Comment by jakub-wojciechowski** [comment]
I'd love to help with this issue. Expect a PR soon :)

**Comment by frangio** [comment]
Awesome @jakub-wojciechowski! I was going to add an example as part of #333 but I'll let you do it.

**Comment by frangio** [comment]
@jakub-wojciechowski Do you have an ETA? Let me know if I can help.

**Comment by jakub-wojciechowski** [comment]
Sorry for the little delay @frangio. I'm just relocating to another country. Let me know if you have any comments.

**Comment by rstormsf** [comment]
Ohh I already have done that with my personal project, I will dig into it after defcon
