### ISSUE TITLE
Crowdsale fails tests 

### ISSUE THREAD

**Issue by Moejoe90** [OpenZeppelin/zeppelin-solidity#343]
when i run `truffle test` on the crowdsale contract 
i receive 
`Error: VM Exception while processing transaction: invalid opcode `

**Comment by Moejoe90** [comment]
Solved

**Comment by frangio** [comment]
For the record, this was probably caused by lack of funds in testrpc. You should be running `npm test` which loads enough funds.

**Comment by Moejoe90** [comment]
Yes that was exactly the case @frangio thanks for your reply
