### ISSUE TITLE
MintableToken doesn't emit Transfer event

### ISSUE THREAD

**Issue by SylTi** [OpenZeppelin/zeppelin-solidity#344]
Hey there !
To be fully ERC20 compliant a mintable token should emit a Transfer event, not a Mint event.
From ERC20: 
"A token contract which creates new tokens SHOULD trigger a Transfer event with the `_from` address set to `0x0` when tokens are created.
*Note* Transfers of 0 values MUST be treated as normal transfers and fire the `Transfer` event."
see https://github.com/ethereum/EIPs/pull/610/files

I will do a pull request if I have the time this week.

**Comment by frangio** [comment]
Thanks a lot for reporting @SylTi! 😄 

Technically, this is marked as `SHOULD` in the standard (as opposed to `MUST`), so I'd say `MintableToken` is compliant regardless. However, as we've discussed in [Slack](http://slack.openzeppelin.org/), the `Transfer` event seems to be picked up by Etherscan to show balances in their ERC20 web interface. For this reason we think it would be particularly beneficial to add the event.

We can still emit a `Mint` event, though. And we should for backward compatibility.

We'll be happy to accept your PR!
