### ISSUE TITLE
finishMinting()?

### ISSUE THREAD

**Issue by tloriato** [OpenZeppelin/zeppelin-solidity#356]
Hey guys,I'm sorry to disturb the things around here, I see that you are pretty organized. I was wondering if I could get an overview over the `finishMinting()` function? I don't comprehend its purpose or why it should exists.

```
  /**
   * @dev Function to stop minting new tokens.
   * @return True if the operation was successful.
   */
  function finishMinting() onlyOwner returns (bool) {
    mintingFinished = true;
    MintFinished();
    return true;
  }
```

**Comment by Ivshti** [comment]
Allowing the owner of the smart contact to stop the minting is something that can enforce trust in a given token.
For example, if you've promised to create tokens for your advisors after a crowdsale, you can do so and afterwards revoke your ability to mint new tokens, therefore ensuring that you can't theoretically continue minting for your own gain

**Comment by tloriato** [comment]
Oh, I understand now. I thought it was a sub-state of a given time during execution. Thank you  @Ivshti !
