### ISSUE TITLE
Errors in npm dependencies

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/zeppelin-solidity#359]
The output of `npm list` shows two error messages:
> npm ERR! missing: ethereumjs-vm-sc@git+https://github.com/sc-forks/ethereumjs-vm-sc.git#303, required by web3-provider-engine@8.1.19
> npm ERR! extraneous: ethereumjs-vm@2.0.2 /home/frangio/scs/zeppelin/update-truffle-3.4.8/node_modules/solidity-coverage/node_modules/web3-provider-engine/node_modules/ethereumjs-vm

I think this is related to the [forked packages](https://github.com/sc-forks) that solidity-coverage depends on. My guess is that npm is getting confused somehow because a lot of them are named the same way as the official packages.

- [provider-engine-sc](https://github.com/sc-forks/provider-engine-sc/blob/master/package.json#L2)
- [ethereumjs-vm-sc](https://github.com/sc-forks/ethereumjs-vm-sc/blob/master/package.json#L2)

(There may be others.)

@cgewecke can you look into this? The sc-forks repositories don't have issue trackers were I can report it.

**Comment by cgewecke** [comment]
@frangio - I'll open a PR bumping you to the latest solidity-coverage. It uses a version of testrpc 4.x that webpack bundles all the deps.

**Comment by frangio** [comment]
Thanks for the prompt response @cgewecke! That fixed it. 😃
