### ISSUE TITLE
Transfer and Approve events are slightly different from ERC20 standard wiki (missing _)

### ISSUE THREAD

**Issue by yaronvel** [OpenZeppelin/zeppelin-solidity#370]
For example, you are using `from` instead of `_from` in `Transfer` event.
See wiki [here](https://theethereum.wiki/w/index.php/ERC20_Token_Standard).

It could cause problems when parsing events with web3.
However, I am guessing this standard is not strictly followed and devs cannot rely on it anyway.

**Comment by frangio** [comment]
Thanks for reporting @yaronvel!

I've noticed this before, but I don't think it's an issue. The argument names are not included in the actual event data. They're only used when _decoding_ it at the application level. See web3's [`decode`](https://github.com/ethereum/web3.js/blob/6d3e61a010501011a107a79574cc7516900fa9e4/lib/web3/event.js#L140-L165) function. The event data is in two arrays which are "zipped" together with the names in ABI.

**Comment by yaronvel** [comment]
Yeah, it is very minor issue.
I encountered it when my truffle test failed for unknown field name. So it does have (minor) meaning.

Anyway, just wanted to let you know. As you are already aware of it, i will close the issue.

**Comment by frangio** [comment]
What do you mean with the unknown field name? Is it posible that it said `<indexed>` ?

**Comment by yaronvel** [comment]
If I use `log.args._from.valueOf()` it throws an exception as `log.args._from` is undefined.
So I have to use `log.args.from.valueOf()`.
This is the full code:

```
        return tokenContract.transfer( reciver.address, amount, {from: sender.address} ).then(function(result){
            if( shouldFail ) {
                assert.fail("expecting transfer to fail");
            }
            
            assert.equal(result.logs.length, 1, "expected a single event");
            var log = result.logs[0];            
            assert.equal(log.event, "Transfer", "unexpected event");
            assert.equal(log.args.from.valueOf(), sender.address.valueOf(), "unexpected from address");
            assert.equal(log.args.to.valueOf(), reciver.address.valueOf(), "unexpected to address");
            assert.equal(log.args.value.valueOf(), amount.valueOf(), "unexpected amount");         
```
