### ISSUE TITLE
List of ICOs that have used OpenZeppelin?

### ISSUE THREAD

**Issue by appjitsu** [OpenZeppelin/zeppelin-solidity#383]
Can you provide a list of successful ICOs that have used OpenZeppelin in full or at least in part?

**Comment by frangio** [comment]
Hi @appjitsu! @demibrener might have such a list handy.

**Comment by demibrener** [comment]
There's no such thing as a formal list, but projects I know that have used OpenZeppelin - in full or in part - include Aragon, Storj, Civic, Tierion and Augur (migrated their token to OpenZeppelin recently).
I'm sure there are many more projects using it that I forgot or I'm not aware of. It would be great to have some sort of tool that looks at Etherscan and can identify OpenZeppelin contracts deployed.

**Comment by Ivshti** [comment]
Adex (https://GitHub.com/adexblockchain ) is using openzeppelin both for it's token sale (conducted successfully in June) and for its product's smart contracts (released on github)
