### ISSUE TITLE
Make decimals uint8 in token example

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/zeppelin-solidity#396]
The decimals variable should be `uint8` according to [ERC20 spec](https://github.com/frozeman/EIPs/blob/94bc4311e889c2c58c561c074be1483f48ac9374/EIPS/eip-20-token-standard.md#decimals). https://github.com/OpenZeppelin/zeppelin-solidity/blob/f45a4e824363718fc625c519cc3db9268a7263ab/contracts/examples/SimpleToken.sol#L17

**Comment by androolloyd** [comment]
https://github.com/OpenZeppelin/zeppelin-solidity/pull/405

**Comment by androolloyd** [comment]
this ticket can be closed, i didn't reference the issue when committing, or in my PR, sorry about that.
