### ISSUE TITLE
Use "grains" to talk about token's smallest unit in docs

### ISSUE THREAD

**Issue by maraoz** [OpenZeppelin/zeppelin-solidity#399]

**Comment by frangio** [comment]
This came out of the [Tierion Network Token audit](https://blog.zeppelin.solutions/tierion-network-token-audit-163850fd1787):
>Giving a name to the smallest transferable unit of a token, in your case _grain_, is a great idea. It eliminates a common ambiguity when talking about token amounts. More projects should do this.

My understanding, however, was that "grain" was coined specifically for the TNT token and not meant as a general-purpose word for all tokens. It would be ideal to have one such word but I don't think "grain" should be it. It also may not make sense given that different tokens have different amount of decimals.

**Comment by Shrugs** [comment]
`bits`?

**Comment by frangio** [comment]
I like @Shrugs proposal. It's specific to each token, however, and it won't require any changes in this repository.
