### ISSUE TITLE
Add Versioning mechanism

### ISSUE THREAD

**Issue by gleim** [OpenZeppelin/zeppelin-solidity#41]
Pulling zeppelin-solidity into a project does not support any visibility into which version of zeppelin-solidity is actually being used

**Comment by maraoz** [comment]
What about the version in package.json?

**Comment by gleim** [comment]
If installation is performed following steps from the README (i.e., `npm i
zeppelin-solidity`) then this package.json artifact is not available to the
project utilizing ZS.  FYI
ᐧ

**Comment by maraoz** [comment]
Aaaah, you're right!

**Comment by frangio** [comment]
Closing since we haven't found the need for this.
