### ISSUE TITLE
Existing Token giveaway contract?

### ISSUE THREAD

**Issue by iTokens** [OpenZeppelin/zeppelin-solidity#414]
I have a token, and I want to do a free ico giveaway like, even of someone sends me even the smallest amount of ether possible, even 0, I want to send them back 1000 of my token. The Token is already issued, and I'm also not sure if it is possible to deploy a second contract on a token that's already been created. Is there an existing script in OpenZepplin I can use for something like this?

**Comment by frangio** [comment]
Hi @iTokens! There is no contract in OpenZeppelin that will allow you to do this. It should be a very simple contract that you can write in just a few lines of code. 🙂

**Comment by iTokens** [comment]
@frangio So far we have the following for the faucet address, can you please advise:

```
contract FaucetAgent {
    ERC20 token;

    function FaucetAgent(ERC20 _token) {
        token = _token;
    }

    function () public payable {
        require(msg.value > 0);
        token.transfer(msg.sender, 1000);
    }
}
```

**Comment by iTokens** [comment]
@frangio  I am having transaction errors when using the code I pasted, when sending and receiving ethereum, do you see any errors in the code?

**Comment by frangio** [comment]
Please don't use the issue tracker for general questions about Ethereum development. We'll be glad to continue the discussion in our Slack, perhaps in the #beginners channel. 😊

slack.openzeppelin.org
