### ISSUE TITLE
How can I migrate contract which inherits RefundableCrowdsale?

### ISSUE THREAD

**Issue by fjchen7** [OpenZeppelin/zeppelin-solidity#418]
### Problem

I follow the tutorial [How To Create Token and Initial Coin Offering Contracts Using Truffle + OpenZeppelin](https://blog.zeppelin.solutions/how-to-create-token-and-initial-coin-offering-contracts-using-truffle-openzeppelin-1b7a5dae99b6) and want to deploy a contract which inherits `RefundableCrowdsale`.

This is my contract file named `GustavoCoinCrowdsale.sol`
```javascript
pragma solidity ^0.4.11;
import './GustavoCoin.sol';
import 'zeppelin-solidity/contracts/crowdsale/RefundableCrowdsale.sol';

contract GustavoCoinCrowdsale is RefundableCrowdsale {
  function GustavoCoinCrowdsale(uint256 _goal) RefundableCrowdsale(_goal) {}
  function createTokenContract() internal returns (MintableToken) {
    return new GustavoCoin();
  }
}
```
Here I can passing compiling `GustavoCoinCrowdsale.sol`.

This is my deploy file named `2_deploy_contracts.js`
```javascript
var GustavoCoinCrowdsale = artifacts.require("./GustavoCoinCrowdsale.sol")

module.exports = function(deployer, network, accounts) {
  deployer.deploy(GustavoCoinCrowdsale, 10000)
}
```
However, when I use `truffle migrate`, error happens.

```
Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... 0xad88b8e7579f94215c683f3f3eb82afd4b12009a9d79c60b4907191f668a7db8
  Migrations: 0x0c52c1b7da76719d48fac86fee6dc5f1a85e0aac
Saving successful migration to network...
  ... 0x7563a80b3f7ceb6fc7cade34037ac8a3f2b45384e4f3d030b3420188461360ad
Saving artifacts...
Running migration: 2_deploy_contracts.js
  Deploying GustavoCoinCrowdsale...
  ... 0x623b205ce6996985b971ae05b1cd2c191f72e798f1c0896d6e171d52924334cb
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: The contract code couldn't be stored, please check your gas amount.
    at Object.callback (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:222830:46)
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:35149:25
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:224768:9
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:66971:11
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:208348:9
    at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:209773:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:67130:18)
    at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:67420:12)
    at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:67575:12)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:67535:24)
```
How can I solve this error?

### Confusion

By the way, I find that the contract `Crowdsale.sol` have a 4-parameters constructor
```javascript
contract Crowdsale {
  function Crowdsale(uint256 _startBlock, uint256 _endBlock, uint256 _rate, address _wallet) {
    require(_startBlock >= block.number);
    ....
    wallet = _wallet;
  }
}
```
and the inheriting chain is `Crowdsale.sol`->`FinalizableCrowdsale`->`RefundableCrowdsale`.
`RefundableCrowdsale.sol` overwrites his constructor which only have 1 parameter and also use variable `wallet`. I don't know where `wallet` is initialized.
```javascript
contract RefundableCrowdsale is FinalizableCrowdsale {
  function RefundableCrowdsale(uint256 _goal) {
    require(_goal > 0);
    vault = new RefundVault(wallet);
    goal = _goal;
  }
}
```
Does it means that I need 5 parameters (4 of Crowdsale plus 4 of itself), to create a new instance of `RefundableCrowdsale`?

**Comment by frangio** [comment]
Hi @fjchen7!

Please take a look at the [SampleCrowsale](https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/examples/SampleCrowdsale.sol#L34-L37) example. Notice how all the parent constructors are called. It's not that `RefundableCrowdsale` _overrides_ the `Crowdsale` constructor with less arguments, but that it leaves the `Crowdsale` constructor uncalled so that you have to call it yourself.

You should add:
<code>function GustavoCoinCrowdsale(__...__, uint256 _goal) __Crowdsale(...)__ RefundableCrowdsale(_goal) {}
</code>

**Comment by fjchen7** [comment]
Hi @frangio
Must I

**Comment by fjchen7** [comment]
Hi, @frangio
I got it. Thank you!
