### ISSUE TITLE
StandardToken TransferFrom test has failed

### ISSUE THREAD

**Issue by iam-dev** [OpenZeppelin/zeppelin-solidity#419]
Error:

> 1) Contract: StandardToken StandardToken #3 should return correct balances after transfering from another account:
>      Error: VM Exception while processing transaction: invalid opcode
>       at Object.InvalidResponse (/Users/iamdev/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:37295:16)
>       at /Users/iamdev/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:224765:36
>       at /Users/iamdev/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:208348:9
>       at XMLHttpRequest.request.onreadystatechange (/Users/iamdev/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:209773:13)
>       at XMLHttpRequestEventTarget.dispatchEvent (/Users/iamdev/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:67130:18)
>       at XMLHttpRequest._setReadyState (/Users/iamdev/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:67420:12)
>       at XMLHttpRequest._onHttpResponseEnd (/Users/iamdev/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:67575:12)
>       at IncomingMessage.<anonymous> (/Users/iamdev/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:67535:24)

```
it('StandardToken #3 should return correct balances after transfering from another account', async function() {
    console.log("StandardToken #3 BEGIN==========================================================");

    let token = await StandardTokenMock.new(MAIN_ACCOUNT, INITAL_SUPPLY);

    let mainAccountBalanceBeforeTransfer = await token.balanceOf(MAIN_ACCOUNT);
    console.log("mainAccountBalanceBeforeTransfer=" +mainAccountBalanceBeforeTransfer);
    assert.equal(mainAccountBalanceBeforeTransfer, INITAL_SUPPLY);

    let ReceivingAccountBalanceBeforeTransfer = await token.balanceOf(RECEIVING_ACCOUNT);
    console.log("ReceivingAccountBalanceBeforeTransfer=" +ReceivingAccountBalanceBeforeTransfer);
    assert.equal(ReceivingAccountBalanceBeforeTransfer, 0);

    let spenderAccountBalanceBeforeTransfer = await token.balanceOf(SPENDER_ACCOUNT);
    console.log("spenderAccountBalanceBeforeTransfer=" +spenderAccountBalanceBeforeTransfer);
    

    await token.approve(SPENDER_ACCOUNT, APPROVE_AMOUNT);
    console.log("APPROVE_AMOUNT " +APPROVE_AMOUNT);

    let allowance = await token.allowance(MAIN_ACCOUNT, SPENDER_ACCOUNT);
    console.log("Allowance = " +allowance +"  of SPENDER_ACCOUNT");
    assert.equal(allowance, APPROVE_AMOUNT);
    
    await token.transferFrom(MAIN_ACCOUNT, RECEIVING_ACCOUNT, TRANSFER_AMOUNT, {from: SPENDER_ACCOUNT});
    console.log("TransferFrom " +TRANSFER_AMOUNT +" MAIN_ACCOUNT to RECEIVING_ACCOUNT from SPENDER_ACCOUNT")
    
  });
```

**Comment by iam-dev** [comment]
I've copied the original test and truffle tested it.
It works. 

Then I put back my own test code and it also works.. Some kind of hicked up??!

**Comment by frangio** [comment]
Hi @iam-dev! I didn't quite follow. Was there a problem?
