### ISSUE TITLE
Which contract can be used for swap between ETH and Token.

### ISSUE THREAD

**Issue by y-zono** [OpenZeppelin/zeppelin-solidity#422]
I want to swap between Ether and Token like the following use case. Which contracts of zeppelin-solidity can be used?

Actors

```
Alice: Blogger. She wants to issue BloggerToken. BloggerToken allows token holders to read special articles of Alice's Blog.
Bob: A fan of Alice blog. He wants to get BloggerToken so that he can read the special articles.
```

Use Case

```
1. Bob sent 1 ETH to Alice.
2. Bob receive 10 BloggerToken.
```

**Comment by frangio** [comment]
Hi @y-zono! It sounds like a "continuous sale" model. We don't have an implementation of it in OpenZeppelin at the moment but you should check out [decentraland/mana](https://github.com/decentraland/mana)'s [ContinuousSale](https://github.com/decentraland/mana/blob/master/contracts/ContinuousSale.sol).

**Comment by y-zono** [comment]
@frangio Thanks! Seems that is what I wanted. I will try to use it.
