### ISSUE TITLE
Comments for whenNotPaused and whenPaused are confusing

### ISSUE THREAD

**Issue by kkx** [OpenZeppelin/zeppelin-solidity#425]
https://github.com/OpenZeppelin/zeppelin-solidity/blob/b07466a4777297a47bed894c487847a4ce201076/contracts/lifecycle/Pausable.sol#L19-L27

```
 /**
   * @dev modifier to allow actions only when the contract IS paused
   */
  modifier whenNotPaused() {

/**
   * @dev modifier to allow actions only when the contract IS NOT paused
   */
  modifier whenPaused() {
```

i think should reverse these two comments

**Comment by frangio** [comment]
Thank you @kkx! Has been fixed in #428.
