### ISSUE TITLE
Why different branch is npm packaged?

### ISSUE THREAD

**Issue by 7flash** [OpenZeppelin/zeppelin-solidity#427]
"npm install zeppelin-solidity" clone "crowdsale-whitelisted" branch. It makes a lot of confusion for me

**Comment by frangio** [comment]
Hi @7flash. I'm quite sure it's not installing that branch. It is installing the latest version which is behind `master`.

**Comment by 7flash** [comment]
I was confusing by changing from "startBlock" to "startTime". So this change is planned for next release?

**Comment by frangio** [comment]
Yes! 😃
