### ISSUE TITLE
Improper use of assert() in BasicToken and other places

### ISSUE THREAD

**Issue by mikhail-vladimirov** [OpenZeppelin/zeppelin-solidity#435]
Method `transfer` of `BasicToken` smart contract uses method `sub` defined in `SafeMath` library to implicitly check that sender's balance is enough to transfer:

    balances[msg.sender] = balances[msg.sender].sub(_value);

Method `sub` internally uses `assert()` function like this (`a` and `b` and method parameters):

    assert(b <= a);

So, when sender's balance is insufficient, assert will fail and execution will be aborted.  According to Solidity docs:

> assert(bool condition): abort execution and revert state changes if condition is false (use for internal error)

but insufficient sender's balance is not internal error, so `assert()` should not be used here.

Note, that `require()` does not fit as well because:

> require(bool condition): abort execution and revert state changes if condition is false (use for malformed input or error in external component)

and insufficient sender's balance is neither malformed input, not error in external component.  So the best fit would be to use `revert()` here.

**Comment by frangio** [comment]
Thanks for reporting @mikhail-vladimirov! I agree with your assessment. Do you want to submit a PR changing to `revert`?

**Comment by mikhail-vladimirov** [comment]
@frangio I'm personally strongly for return false versus revert(), my motivation is here: https://github.com/ethereum/EIPs/pull/610#issuecomment-305770167.  So I prefer somebody else to submit this PR.

**Comment by facuspagnuolo** [comment]
@nedodn sorry to disagree, require is meant to be used for validations, while assert should be used in order to prevent conditions which should never be possible, in this case, we are preventing an overflow.

I highly recommend this article, a detailed explanation about this subject.

**Comment by b-mueller** [comment]
Sorry to re-vitalize this old issue but I agree @3sGgpQ8H and @frangio. `assert` is meant assert invariants, i.e. conditions that are impossible to occur. If there's a way to violate and invariant it *always* means that there's a bug in the code.

The asserts in SafeMath are implicitly performing input validation and IMO should be replaced by `require`.

**Comment by b-mueller** [comment]
Ahh, I didn't notice! Awesome :)
