### ISSUE TITLE
TokenTimelock allows anyone to initiate tokens release

### ISSUE THREAD

**Issue by mikhail-vladimirov** [OpenZeppelin/zeppelin-solidity#441]
`TokenTimelock` smart contract has two public methods: `claim()` and `release()` that do basically the same thing, but `claim()` reverts transaction unless called by beneficiary of the smart contract, while `release()` may be called by anyone.  According to comment in the code

> TokenTimelock is a token holder contract that will allow a beneficiary to extract the tokens after a given release time

While it is not explicitly specified that token extractions must be initiated by beneficiary only, assuming the opposite will mean that `claim()` method does not make any sense.  So, assuming that this smart contract allows beneficiary and only beneficiary to initiate token extraction, method `release()` should be declared as `internal` or `private`.

**Comment by frangio** [comment]
`claim` is deprecated. Please see #296.

We should change the contract description if this is not clear.

**Comment by maraoz** [comment]
Closing, as `claim` was removed.
