### ISSUE TITLE
RefundVault.sol functions should be declared public explicitly

### ISSUE THREAD

**Issue by SylTi** [OpenZeppelin/zeppelin-solidity#444]
best practice require to always declare explicitly the visibility.
Also shouldn't `function refund(address investor)` also have the onlyOwner modifier? It's not a problem security wise, but refunds are meant to be handled directly by the crowdsale

**Comment by SylTi** [comment]
this seems to be a larger problem, I spotted a bunch of file where function accessibility is not explicit when public

**Comment by frangio** [comment]
Fixed in #456.
