### ISSUE TITLE
BurnableToken improvements

### ISSUE THREAD

**Issue by daniel-jozsef** [OpenZeppelin/zeppelin-solidity#463]
In my opinion the _BurnableToken_ implementation is not quite up to the standards of OpenZeppelin. My issues with it are:

- It inherits from _StandardToken_ as opposed to _BasicToken_, while not using any of the added functionality. I suggest either implementing _burnFrom()_, or changing the ancestor to _BasicToken_.

- _burn()_ does not have a return value, and misuses _assert()_. Generally, _assert()_ should only be used in cases where a false condition is theoretically impossible, as a guard of last resort. So additional _require()_ statements should be added to check if the amount to be burned is not greater than the amount of token available in the first place. Also, since there is a possibility that the function will throw, a _(bool success)_ should be returned as per solidity best practices.

**Comment by frangio** [comment]
Thanks for the feedback @daniel-jozsef!

Agree with changing the ancestor to `BasicToken`. Do you want to submit a PR with this change?

With respect to `assert`, for anyone reading, it's hidden under `SafeMath.sub`. I agree that it doesn't seem correct. I was just discussing yesterday whether `assert` or `require` would be the correct semantics for `SafeMath`. I'm going to open a separate issue for this more general problem.

I've never heard of the Solidity best practice of returning a `bool success`. Is this written down somewhere? In fact, we consider boolean return values problematic because they often go unchecked. I would agree that it's the pattern in ERC20, but `burn` doesn't necessarily have to be consistent with that.

**Comment by daniel-jozsef** [comment]
I think assert is correct in SafeMath, as it is checking for under-, and overflows. It's a technical check for a technical limitation.

BurnableToken, however, relies on the underflow protection to do a _semantic_ check of its inputs, which I see as bad practice. There should either be a require call _in the burn() function_ to validate user input, or logic to _burn the available amount, but not more_ in case the amount requested to be burned is higher than the amount available.

As for returning _bool_, correct me if I'm wrong, but Solidity exceptions do not bubble up. A function call that "throws" just silently fails, reverting its own state changes, but not those of its caller. Which means without a return value, there is no way to tell at all whether a call has succeeded or failed.

**Comment by rstormsf** [comment]
`assert` vs `require` 
As I understand, based on solidity documentation, `require` should be used for checking external calls.

`assert` should be used for internal validation checks.

Please correct me if I’m wrong.

 ``` The assert function should only be used to test for internal errors, and to check invariants. The require function should be used to ensure valid conditions, such as inputs, or contract state variables are met, or to validate return values from calls to external contracts. 
```
https://solidity.readthedocs.io/en/develop/control-structures.html#error-handling-assert-require-revert-and-exceptions

**Comment by daniel-jozsef** [comment]
Okay apparently I was misinformed on exception handling in the EVM.

> When exceptions happen in a sub-call, they “bubble up” (i.e. exceptions are rethrown) automatically. Exceptions to this rule are send and the low-level functions call, delegatecall and callcode – those return false in case of an exception instead of “bubbling up”. (from the Solidity 0.4.18 docs)

Apparently errors do not bubble up through call, delegatecall and callcode. Which, as far as I understand, means all cross-contract calls, ie. the only time an error does bubble up is when calling a function on _this_.

**Comment by Qqwy** [comment]
> It inherits from StandardToken as opposed to BasicToken, while not using any of the added functionality. I suggest either implementing burnFrom(), or changing the ancestor to BasicToken.

I think this third option is the most versatile one: Have `BurnableToken` inherit from `BasicToken`, but also have an  `ApprovedBurnableToken` that inherits from both `BurnableToken` and `StandardToken` and implements the `burnFrom()` function.

This would allow people that use the library to pick the exact granularity of functionality they require for their projects.

**Comment by Qqwy** [comment]
@daniel-jozsef Important here (with how thrown errors bubble up) is IIRC also a possible difference with how Solidity/the EVM currently works, and how it is expected to be altered and behave in the near future.

**Comment by ajsantander** [comment]
@daniel-jozsef did you manage to implement any of this in a PR?
