### ISSUE TITLE
Some aspects not complying with Solidity style guide.

### ISSUE THREAD

**Issue by cbruguera** [OpenZeppelin/zeppelin-solidity#474]
There are elements in the code that don't comply with the Solidity proposed style guide. For example, 2 spaces instead of 4 as a tab unit. Also, some constants not in UPPER_CASE format (at least in the token example file).

I understand style guides are never mandatory and in fact should be flexible enough as to accomodate for particular needs, but if we're aiming to standardize Solidity development, I think there should be an agreement on the matter... Any thoughts on that?

**Comment by rickie247** [comment]
I agree with you, but yet you should always do your own checks and make sure the code is correct.

**Comment by Qqwy** [comment]
The most important with any kind of group coding effort is that the style used in the repository is consistent.

**Comment by cbruguera** [comment]
If the coding effort is an effort aimed at providing a standard for development in a given language, I do think it's more or less relevant that there is some degree of consensus with the style conventions of such language. In any case, I'd only wish to be acquainted with the stance of the developers on this regard, whether it's purposedly assuming particular styling guidelines or not. I'm just pointing out to this discrepancy to know how relevant it is considered by the community.

**Comment by maraoz** [comment]
We prefer 2 spaces over 4, and I don't think we'll change that.
As for UPPER_CASE constants, I opened this new issue: https://github.com/OpenZeppelin/zeppelin-solidity/issues/546
