### ISSUE TITLE
Same pragma compiler version

### ISSUE THREAD

**Issue by lorien** [OpenZeppelin/zeppelin-solidity#486]
All sol files except BurnableToken.sol and BurnableTokenMock.sol declares `pragma compiler ^0.4.11`. The latter two files use `pragma compiler ^0.4.13`.
Maybe it makes sense to use same pragma compiler in all files?

**Comment by maraoz** [comment]
Included in https://github.com/OpenZeppelin/zeppelin-solidity/issues/511
