### ISSUE TITLE
Add SmartToken contract

### ISSUE THREAD

**Issue by AugustoL** [OpenZeppelin/zeppelin-solidity#494]
## Simple Summary

A standard interface for smart tokens based in the ERC20 standard.

## Abstract

This standard provides basic functionality to transfer tokens, as well as allow tokens to be approved so they can be spent by another on-chain third party. Also it allows to execute calls on transfers and approvals.

## Motivation

A standard interface allows any tokens on Ethereum to be re-used by other applications: from wallets to decentralized exchanges. The ERC20 token standard is widely accepted but it only allows the transfer of value, ethereum users are available to transfer value and data on transactions, with these extension of the ERC20 token standard they will be able to do the same with ERC20 tokens.

### Methods

**NOTE**: Callers MUST handle `false` from `returns (bool success)`.  Callers MUST NOT assume that `false` is never returned!

#### name - ERC20

Returns the name of the token - e.g. `"MyToken"`.

OPTIONAL - This method can be used to improve usability,
but interfaces and other contracts MUST NOT expect these values to be present.

``` js
function name() constant returns (string name)
```

#### symbol - ERC20

Returns the symbol of the token. E.g. "HIX".

OPTIONAL - This method can be used to improve usability,
but interfaces and other contracts MUST NOT expect these values to be present.

``` js
function symbol() constant returns (string symbol)
```

#### decimals - ERC20

Returns the number of decimals the token uses - e.g. `8`, means to divide the token amount by `100000000` to get its user representation.

OPTIONAL - This method can be used to improve usability,
but interfaces and other contracts MUST NOT expect these values to be present.

``` js
function decimals() constant returns (uint8 decimals)
```

#### totalSupply - ERC20

Returns the total token supply.

``` js
function totalSupply() constant returns (uint256 totalSupply)
```

#### balanceOf - ERC20

Returns the account balance of another account with address `_owner`.

``` js
function balanceOf(address _owner) constant returns (uint256 balance)
```

#### transfer - ERC20

Transfers `_value` amount of tokens to address `_to`, and MUST fire the `Transfer` event.
The function SHOULD `throw` if the `_from` account balance does not have enough tokens to spend.

A token contract which creates new tokens SHOULD trigger a Transfer event with the `_from` address set to `0x0` when tokens are created.

*Note* Transfers of 0 values MUST be treated as normal transfers and fire the `Transfer` event.

``` js
function transfer(address _to, uint256 _value) returns (bool success)
```

#### transferFrom - ERC20

Transfers `_value` amount of tokens from address `_from` to address `_to`, and MUST fire the `Transfer` event.

The `transferFrom` method is used for a withdraw workflow, allowing contracts to transfer tokens on your behalf.
This can be used for example to allow a contract to transfer tokens on your behalf and/or to charge fees in sub-currencies.
The function SHOULD `throw` unless the `_from` account has deliberately authorized the sender of the message via some mechanism.

*Note* Transfers of 0 values MUST be treated as normal transfers and fire the `Transfer` event.

``` js
function transferFrom(address _from, address _to, uint256 _value) returns (bool success)
```

#### approve - ERC20

Allows `_spender` to withdraw from your account multiple times, up to the `_value` amount. If this function is called again it overwrites the current allowance with `_value`.

Users SHOULD make sure to create user interfaces in such a way that they set the allowance first to `0` before setting it to another value for the same spender.
THOUGH The contract itself shouldn't enforce it, to allow backwards compatilibilty with contracts deployed before

``` js
function approve(address _spender, uint256 _value) returns (bool success)
```

#### allowance - ERC20

Returns the amount which `_spender` is still allowed to withdraw from `_owner`.

``` js
function allowance(address _owner, address _spender) constant returns (uint256 remaining)
```

#### transferData

Execute a function on `_to` with the `_data` parameter, if the function ends successfully execute the transfer of `_value` amount of tokens to address `_to`, and MUST fire the `Transfer` event.
The function SHOULD `throw` if the call to `_to` address fails or if `_from` account balance does not have enough tokens to spend.

*Note* Transfers of 0 values MUST be treated as normal transfers and fire the `Transfer` event.

``` js
function transferData(address _to, uint256 _value, bytes _data) returns (bool success)
```

#### transferDataFrom

Execute a function on `_to` with the `_data` parameter, if the function ends sucesfully execute the transfer of `_value` amount of tokens from address `_from` to address `_to`, and MUST fire the `Transfer` event.

The `transferFrom` method is used for a withdraw workflow, allowing contracts to transfer tokens on your behalf.
This can be used for example to allow a contract to transfer tokens on your behalf and/or to charge fees in sub-currencies.
The function SHOULD `throw` if the call to `_to` address fails or if the `_from` approved balance by `_from` to `msg.sender` is not enough to execute the transfer.

*Note* Transfers of 0 values MUST be treated as normal transfers and fire the `Transfer` event.

``` js
function transferDataFrom(address _from, address _to, uint256 _value, bytes _data) returns (bool success)
```

#### approveData

Execute a function on `_to` with the `_data` parameter, if the function ends sucesfully allows `_spender` to withdraw from your account multiple times, up to the `_value` amount. If this function is called again it overwrites the current allowance with `_value`.

Clients SHOULD make sure to create user interfaces in such a way that they set the allowance first to `0` before setting it to another value for the same spender.
The function SHOULD `throw` if the call to `_to` address fails.
THOUGH The contract itself shouldn't enforce it, to allow backwards compatilibilty with contracts deployed before

``` js
function approveData(address _spender, uint256 _value, bytes _data) returns (bool success)
```

#### Transfer - ERC20

MUST trigger when tokens are transferred, including zero value transfers.

``` js
event Transfer(address indexed _from, address indexed _to, uint256 _value)
```

#### Approval - ERC20

MUST trigger on any successful call to `approve(address _spender, uint256 _value)`.

``` js
event Approval(address indexed _owner, address indexed _spender, uint256 _value)
```

## Implementation

The SmartToken is implemented and used in the Lif token, [Github Repository](https://github.com/windingtree/LifToken)

#### Example implementations are available at
- https://github.com/windingtree/LifToken/blob/master/contracts/SmartToken.sol

**Comment by AugustoL** [comment]
In the case of our project Winding Tree methods like these will allow us to:
* Book hotel rooms or flights in one transaction, executing `transfer` and `book` functions implemented in our contracts.
* Implement approval of bookings, the user will approve the spent of tokens to the hotel, the hotel will accept them if he allows the user to book the room at that price and reject them if not.
* Send encrypted information in token transactions.
* Will allow developers to build more complex apps over our platform.

Also, I've been thinking that this can also help the token to not being take in count as a security, because it will be able to do more that just transfer value between users, but not sure if that is accurate.

**Comment by frangio** [comment]
Hi @AugustoL! I think this proposal is interesting. It's mostly the same as the `transferAndCall` proposal in [ethereum/EIPs#677](https://github.com/ethereum/EIPs/issues/677), right?

**Comment by AugustoL** [comment]
Yes is very similar, I have the EIP already written and ready to proposed, but I wanted to propose it first here, I think it will have more acceptance in the community if we show it working in Zeppelin Solidity.

If you want @frangio I can create the PR to add it tomorrow :)

**Comment by maraoz** [comment]
@AugustoL do `transferData` and `transferDataFrom` use the same function names as `transfer` and `transferFrom`? Why not use the names `transferData` and `transferDataFrom` to avoid confusion?

**Comment by AugustoL** [comment]
@maraoz yes, I was using that names for the methods but forgot to change it here when I was creating the issue, now the issue has the correct function names :)

**Comment by pash7ka** [comment]
SmartToken is the name [used](https://github.com/bancorprotocol/contracts/blob/master/solidity/contracts/SmartToken.sol) by Bancor team for their protocol.
I'm afraid using it here may introduce some confusion.
