### ISSUE TITLE
Add tokensSold to Crowdsale.sol

### ISSUE THREAD

**Issue by fedealconada** [OpenZeppelin/zeppelin-solidity#496]
### Add tokens sold to Crowdsale contract

It would be nice if we could have a variable `uint256 public tokensSold` so as to keep track of the amount of tokens that have been sold so far during a TGE event. 

Then, the `buyTokens()` function should look like:

```
  function buyTokens(address beneficiary) public payable {
    require(beneficiary != 0x0);
    require(validPurchase());

    uint256 weiAmount = msg.value;

    // calculate token amount to be created
    uint256 tokens = weiAmount.mul(rate);

    // update state
    weiRaised = weiRaised.add(weiAmount);
    tokensSold = tokensSold.add(tokens); --> new line

    token.mint(beneficiary, tokens);
    TokenPurchase(msg.sender, beneficiary, weiAmount, tokens);

    forwardFunds();
  }
```
This will have the same philosophy as the `weiRaised` variable... We want to keep track of the wei raised to do checks, to have different crowdsale implementations like `CappedCrowdsale.sol` and  `RefundableCrowdsale.sol`, among others. 

Having the `tokensSold` variable will let us, for instance, have a `CappedOnTokensCrowdsale.sol` or a `RefundableOnTokensCrowdsale.sol` where the `cap` and `goal` (respectively) are expressed in amount of tokens rather than in amount of wei.

**Comment by AugustoL** [comment]
@fedealconada cant you use the totalSupply from the token contract?

**Comment by fedealconada** [comment]
@AugustoL Yes, I thought that afterwards :) But I'm not able to close/remove the issue...

**Comment by AugustoL** [comment]
Cool, yes I agree it can be very helpful to have it.

**Comment by SylTi** [comment]
@fedealconada most of the time people put a hardcap on the sale, when it's the case the max amount of token is something like ` hardcap * rate + percentage` (for founders/advisor etc)

**Comment by Qqwy** [comment]
Some crowdsales actually measure the amount of tokens sold in Tokens rather than in Wei. In the 'simple' case this is equivalent `(tokens = wei * tokenCost)` but when you for instance give out bonus tokens for early adaptors, these two numbers will start to diverge.

**Comment by SylTi** [comment]
@Qqwy those should be counted in the totalSupply 

https://github.com/OpenZeppelin/zeppelin-solidity/pull/426 need to be merged first so we can have a lot more flexibility

**Comment by Qqwy** [comment]
> @Qqwy those should be counted in the totalSupply

Indeed... until this number diverges as well. It is perfectly fine to hold a second crowdsale for an existing token, as long as the crowdsale contract is moved to become the MintableToken's owner, or to hold a crowdsale while already some tokens exist.

I agree that having #426 would be great, and it might be worthwhile to wait for that in order to not repeat work.

**Comment by maraoz** [comment]
Closing given you can just use `token#totalSupply`
