### ISSUE TITLE
Upgradeable contracts

### ISSUE THREAD

**Issue by maraoz** [OpenZeppelin/zeppelin-solidity#5]
See VersionUpgrade, Deprecate and MostRecentVersionAddress in http://vessenes.com/we-need-some-best-practices-for-smart-contracts/

**Comment by akshithg** [comment]
Refer [Setting Standards for Altering and Undoing Smart Contracts](http://www.arijuels.com/wp-content/uploads/2016/06/Setting-Standards-for-Altering-and-Undoing-Smart-Contracts.docx) for stratergies.

**Comment by maraoz** [comment]
More info: https://ethereum.stackexchange.com/questions/2404/upgradeable-contracts

**Comment by verdverm** [comment]
https://blog.zeppelin.solutions/proxy-libraries-in-solidity-79fbe4b970fd

**Comment by maraoz** [comment]
Closing in favor of https://github.com/zeppelinos/labs/
