### ISSUE TITLE
Can solidity process images?

### ISSUE THREAD

**Issue by zrpkid** [OpenZeppelin/zeppelin-solidity#500]
Solidity is a language for smart contacts deployed in Ethereum, It can deal with voting, crowd funding and so on. I wander whether this language can process images? Can this language support some libraries like OpenCV ? Please give me some advice and thank you very much.

**Comment by spalladino** [comment]
@zrpkid this is the issue tracker for OpenZeppelin, a framework to build secure smart contracts on Ethereum, and as such is not the intended place for these kind of questions. Please ask in the [Ethereum stackexchange](https://ethereum.stackexchange.com), or in one of the [Ethereum Gitter channels](https://github.com/ethereum/wiki/wiki/Gitter-Channels).
