### ISSUE TITLE
updagrade to solidity v0.4.17

### ISSUE THREAD

**Issue by maraoz** [OpenZeppelin/zeppelin-solidity#511]
See: https://github.com/ethereum/solidity/releases/tag/v0.4.17

Some things that need to be done:
- change pragma headers.
- Replace occurrences of `constant` with `view` or `pure`.
- add explicit visibility to all functions

**Comment by BrandonGilchrist** [comment]
Can I assume you mean "upgrade to solidity v0.4.**17**" not v0.4.**11**?

**Comment by maraoz** [comment]
@BrandonGilchrist good catch! fixed

**Comment by pash7ka** [comment]
I've commited pull request, but CI build fails on "pure"/"view" keywords. Perhaps it uses the old compiler version.
