### ISSUE TITLE
Unnecessary use of SafeMath in StandardToken

### ISSUE THREAD

**Issue by ritzdorf** [OpenZeppelin/zeppelin-solidity#514]
The issue is for the following line:
https://github.com/OpenZeppelin/zeppelin-solidity/blob/5cf503673faea92c1b5c615c3f8358febf06e160/contracts/token/StandardToken.sol#L81

The use of SafeMath adds the following check:
https://github.com/OpenZeppelin/zeppelin-solidity/blob/f3867f847722b298c360a9a0158c7aa89c7d557c/contracts/math/SafeMath.sol#L23

However, exactly that is checked right before:
https://github.com/OpenZeppelin/zeppelin-solidity/blob/5cf503673faea92c1b5c615c3f8358febf06e160/contracts/token/StandardToken.sol#L78

**Comment by BrandonGilchrist** [comment]
https://github.com/OpenZeppelin/zeppelin-solidity/pull/591 @maraoz @ritzdorf

**Comment by frangio** [comment]
Exactly as Brandon explained.
