### ISSUE TITLE
Crowdsale should divide by rate 

### ISSUE THREAD

**Issue by eepstein** [OpenZeppelin/zeppelin-solidity#521]
Line 74 of the Crowdsale.sol file has:

`    uint256 tokens = weiAmount.mul(rate);`

Shouldn't that instead be:

`    uint256 tokens = weiAmount.div(rate);`

If it takes 1000 wei to buy a token, the number of tokens to issue/mint would be the number of wei sent to buyTokens() divided by the rate.  Right?

Hoping someone (else) can double check this.

**Comment by eepstein** [comment]
Never mind.  The rate is tokens per ether.  The impl now makes sense to me.

**Comment by ericwooley** [comment]
Are we sure this should be closed? 

After following this guide, https://blog.zeppelin.solutions/how-to-create-token-and-initial-coin-offering-contracts-using-truffle-openzeppelin-1b7a5dae99b6

I set the tokens rate to 1000, my understanding is that should be 1000 tokens per ether, but it is actually per wei. So 1 ether = '1e+21' tokens. Which seems a bit high...

I can't seem to pass in a decimal, to force division, so I am a little stuck here. It seems that I am stuck at 1 token per wei, which is one billion billion tokens per ether. Not really numbers I feel like dealing with.

Am i missing something obvious?

**Comment by ericwooley** [comment]
Turns out I'm a durp, but I can explain it for other people I think, who might come here with the same confusion.

I had decimals set to 18. But the contract isn't using floats, so 18 decimals of precision, is actually 18 extra zeros. So in order to get your token amount in truffle, use:
```js
     web3
        .toBigNumber(tokenCount)
        .div('1e+18') // 18 should be whatever number of decimals you have set.
```

**Comment by nionis** [comment]
I would propose to change the crowdsale in this way
https://github.com/nionis/purpose/blob/master/contracts/Crowdsale.sol
Basically there are 2 inputs for rate a/b token/ether
then it does:
weiAmountSend.div(b).mul(a)
