### ISSUE TITLE
Add truffle and yarn versions output to TravisCI job log

### ISSUE THREAD

**Issue by limexp** [OpenZeppelin/zeppelin-solidity#534]
To simplify the search for build errors I suggest to add the following two commands to ```.travis.yml```
```
truffle version
yarn list
```
This information can help to resolve build problems like #491.

I can make a PR if you accept.

**Comment by maraoz** [comment]
Yes, please create the PR

**Comment by frangio** [comment]
Fixed as of #553. (Note that `npm list` is implictily done by Travis so was removed later in 3ad555b.)
