### ISSUE TITLE
How to understand the code "vault.deposit.value(msg.value)(msg.sender);"

### ISSUE THREAD

**Issue by lisuyong** [OpenZeppelin/zeppelin-solidity#539]
Hi, there

I don't understand why [this code](https://github.com/OpenZeppelin/zeppelin-solidity/blob/8e01dd14f9211239213ae7bd4c6af92dd18d4ab7/contracts/crowdsale/RefundableCrowdsale.sol#L34) use ".value(x)" here. I know it's setting the ether value, but why use here?

Thanks, I'm very curious :)

Justin

**Comment by maraoz** [comment]
That's a way of calling the [RefundVault#deposit function](https://github.com/OpenZeppelin/zeppelin-solidity/blob/8e01dd14f9211239213ae7bd4c6af92dd18d4ab7/contracts/crowdsale/RefundVault.sol#L31), which is payable, with a specific `msg.value` amount. 
See: https://ethereum.stackexchange.com/a/9722/3054

**Comment by jacktang** [comment]
@maraoz how can I call `Crowdsale`'s fallback(the payable method without name) function in another contract, say `Presale.sol`. Thanks

**Comment by Shrugs** [comment]
@jacktang http://solidity.readthedocs.io/en/v0.4.21/units-and-global-variables.html?highlight=message%20call#address-related
