### ISSUE TITLE
Add tests for main contracts

### ISSUE THREAD

**Issue by maraoz** [OpenZeppelin/zeppelin-solidity#54]
Missing:
- [x] Killable
- [x] SafeMath
- [x] Shareable https://github.com/OpenZeppelin/zeppelin-solidity/issues/91
- [x] DayLimit https://github.com/OpenZeppelin/zeppelin-solidity/issues/92
- [x] MultisigWallet https://github.com/OpenZeppelin/zeppelin-solidity/issues/93

**Comment by adklempner** [comment]
Working on tests for Killable
