### ISSUE TITLE
Let's extract method from onlyOwner modifier

### ISSUE THREAD

**Issue by k06a** [OpenZeppelin/zeppelin-solidity#540]
I would like to extract onlyModifier behavior out of modifier like this:
```
modifier onlyOwner() {
    if (onlyOwnerMethod(msg.sender)) {
        _;
    }
}

function onlyOwnerMethod(address wallet) internal constant returns (bool) {
    require(wallet == owner);
    return true;
}
```

This will allow to override modifier behavior for example with `Multiownable` smart contract: https://github.com/bitclave/Multiownable

**Comment by federicobond** [comment]
Thanks for the suggestionn @k06a! Ownable already declares a single owner field, so I think we are better off with a separate contract (like Multiownable) for handling other use cases.

**Comment by k06a** [comment]
@federicobond  I am thinking about making possible this case:
```
contract MultiCrowdsale is FinalizableCrowdsale, Multiownable {
}
```
To override `Ownable` with `Multiownable` for some contracts who is already `Ownable`.

**Comment by federicobond** [comment]
For that use case, I suggest you set the owner of the Crowdsale to a Multisig wallet and relay transactions through it. This leaves the logic of both contracts intact and more clearly separates concerns between the two well-audited contracts.

**Comment by k06a** [comment]
@federicobond smart enough 👍

**Comment by k06a** [comment]
@federicobond found a tricky way to override `Ownable` by `Multiownable`. Take a look at `MultisigMintableToken`: https://github.com/bitclave/Multiownable/pull/1
