### ISSUE TITLE
Opinion on checking the parameter in Crowdsale

### ISSUE THREAD

**Issue by rstormsf** [OpenZeppelin/zeppelin-solidity#545]
I was thinking of adding this check:
`    require(beneficiary == msg.sender);`
to 
https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/crowdsale/Crowdsale.sol#L70

Any opinions?
I believe that's if someone calls from low level, we need to make sure they are doing it correctly.

**Comment by frangio** [comment]
Actually the `buyTokens` method is designed so that anyone can execute a purchase for another beneficiary! So the check goes against the intended semantics.

**Comment by rstormsf** [comment]
got it. makes sense.
