### ISSUE TITLE
Is the RefundableCrowdsale constructor incomplete?

### ISSUE THREAD

**Issue by manusmrit** [OpenZeppelin/zeppelin-solidity#560]
https://github.com/OpenZeppelin/zeppelin-solidity/blob/84bffb854a1bdb4735aabd457e97eecc8f3f2d02/contracts/crowdsale/RefundableCrowdsale.sol#L26

I could not find any other references in the contract to the "wallet" parameter?

**Comment by nedodn** [comment]
It is defined in Crowdsale.sol. Since RefundableCrowdsale inherits from FinalizableCrowdsale which inherits from Crowdsale, it has access to the wallet variable there.

**Comment by cannabhakt** [comment]
Aye aye captain:ok_hand:

**Comment by frangio** [comment]
Thanks for answering this @nedodn!
