### ISSUE TITLE
npm install does not create node_modules directory

### ISSUE THREAD

**Issue by ruby32** [OpenZeppelin/zeppelin-solidity#567]
## Problem
Following the instructions to install zeppelin-solidity, the `node_modules` directory is not created.

## Expected results
The `node_modules` directory is populated.

## Actual results
After running `truffle init` successfully, running `npm install zeppelin-solidity` does not return an error, but it does have a ton of warnings:

```
$ npm install zeppelin-solidity
npm WARN saveError ENOENT: no such file or directory, open '/home/ubuntu/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/ubuntu/package.json'
npm WARN uglifyjs-webpack-plugin@1.0.1 requires a peer of webpack@^2.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ubuntu No description
npm WARN ubuntu No repository field.
npm WARN ubuntu No README data
npm WARN ubuntu No license field.

+ zeppelin-solidity@1.3.0
updated 1 package in 0.903s
$ ls -l
total 20
drwxrwxr-x 2 ubuntu ubuntu 4096 Nov 17 20:20 contracts
drwxrwxr-x 2 ubuntu ubuntu 4096 Nov 17 20:07 migrations
drwxrwxr-x 2 ubuntu ubuntu 4096 Nov 17 20:07 test
-rw-rw-r-- 1 ubuntu ubuntu  135 Nov 17 20:07 truffle-config.js
-rw-rw-r-- 1 ubuntu ubuntu  135 Nov 17 20:07 truffle.js
```

The `node_modules` directory is not created as expected.

## System details:

Ubuntu 16.04
npm 5.5.1
nodejs v8.9.1
truffle v4.0.1
zeppelin-solidity 1.3.0

**Comment by frangio** [comment]
Please see #475. Run `npm init` before installing.

I will add this to the README. We didn't realize it was missing there.
