### ISSUE TITLE
Crowdsale Token Error

### ISSUE THREAD

**Issue by parsparab** [OpenZeppelin/zeppelin-solidity#570]
I'm getting this error in remix solidity browser, not able to deploy the crowdsale contract.
creation of browser/Crowdsale.sol:Crowdsale errored: Gas required exceeds limit: 3000000. An important gas estimation might also be the sign of a problem in the contract code. Please check loops and be sure you did not sent value to a non payable function (that's also the reason of strong gas estimation).

**Comment by steven0610** [comment]
did you fix it ?

**Comment by Shrugs** [comment]
@parsparab please provide any information that would help us figure out what's going wrong. You can't expect anyone to help from such a general description of the problem and error message.

Provide us with

- contract code that you're trying to deploy
- which remix settings are you using?
- which chain are you deploying to?
- as much information as possible.

I'll reopen the issue when we have more information.

**Comment by parsparab** [comment]
Ya, i have solved it by changing the gas price.

**Comment by pascal1990** [comment]
@parsparab  Hi have this problem, when trying to send ether to the contract, contract is already deploy, using address contract to interact and send ether. please could you help me
