### ISSUE TITLE
Problem: unused variable `remaining` in StandardToken.sol

### ISSUE THREAD

**Issue by rstormsf** [OpenZeppelin/zeppelin-solidity#572]
https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/token/StandardToken.sol#L60

```javascript
  function allowance(address _owner, address _spender) public constant returns (uint256 remaining) {
    return allowed[_owner][_spender];
  }
```

**Solution:**
either assign to a variable: 
```
  function allowance(address _owner, address _spender) public constant returns (uint256 remaining) {
    remaining = allowed[_owner][_spender];
  }
```
**OR** 
remove name of unused variable

```
  function allowance(address _owner, address _spender) public constant returns (uint256) {
    return allowed[_owner][_spender];
  }
```

**UPDATE**:
There are also the same issues for methods: `increaseApproval`, `decreaseApproval`.
Unused variable `success` 
https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/token/StandardToken.sol#L70
https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/token/StandardToken.sol#L76

**Comment by gakonst** [comment]
Fixed!

**Comment by frangio** [comment]
Thanks for reporting @rstormsf!
