### ISSUE TITLE
Re-enable solidity-coverage

### ISSUE THREAD

**Issue by ajsantander** [OpenZeppelin/zeppelin-solidity#575]
See PR #573 (Update to truffle 4.0.0 and solc 0.4.18)

solidity-coverage is not compatible with the latest solc versions without forcing tests to use .call(), so we had to disable it on travis. 

We should re-enable coverage tests after the issue is resolved in solidity-coverage. Will post commit that should be reverted to re-enable coverage.

**Comment by ajsantander** [comment]
Undo this commit when solidity-coverage is compatible with solc 0.4.18
https://github.com/OpenZeppelin/zeppelin-solidity/commit/0eaa5f50ace9b3b1adf888fb0733589d5ac02e39

**Comment by cgewecke** [comment]
@ajsantander Hi. Latest solidity-coverage (`0.4.3`) is now compatible with the newer solc versions thanks to thoughtful suggestions from the Zeppelin team. Example of a successful CI run on our zeppelin fork [here](https://travis-ci.org/sc-forks/zeppelin-solidity/builds/313623927).

Unfortunately there are some caveats if you decide to re-enable: `.sol` mock contracts will need to be moved from the `test` folder to the `contracts` folder, probably added to an .npmignore, and lots of paths rewritten. 

Additionally, the `.solcover.js` should be revised as below:
```javascript
module.exports = {
    norpc: true,
    testCommand: 'node --max-old-space-size=4096 ../node_modules/.bin/truffle test --network coverage',
    compileCommand: 'node --max-old-space-size=4096 ../node_modules/.bin/truffle compile --network coverage',
    skipFiles: [
      'lifecycle/Migrations.sol',
      'helpers' // <-- This a folder containing the mocks (obviously any name is fine).
    ]
}
```

Very sorry that these changes are necessary. If you or anyone else would like to discuss this further - we have a [gitter channel](https://gitter.im/sc-forks/solidity-coverage) now. Happy to discuss or make improvements if possible. 

Thanks again for your help @spalladino @frangio :)

**Comment by spalladino** [comment]
Working on this on https://github.com/spalladino/zeppelin-solidity/tree/feature/reenable-coverage. I fixed the paths issue by symlinking the mocks folder. However, there are a handful of tests failing. I'll look into it and send a PR as soon as I've fixed it.
