### ISSUE TITLE
Reason for permitting purchases for address other than msg.sender?

### ISSUE THREAD

**Issue by NoahMarconi** [OpenZeppelin/zeppelin-solidity#578]
I'm working on a project with KYC requirements and am considering overriding the ability for the purchase to be from an address other than the token receiver.

Before I override I wanted to check to be certain there's nothing important I'm missing. Does anyone know the motivation behind making the low level buyTokens method public? If I were to override and make it private, or otherwise remove the ability to send ETH from one address and receive tokens at another, are there important considerations that I'm missing?

https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/crowdsale/Crowdsale.sol#L69

**Comment by NoahMarconi** [comment]
Pining @maraoz as I see you're the first to commit that particular method in the repo.

**Comment by maraoz** [comment]
We separated the purchasing address from the beneficiary address to allow the creation of software that buys tokens for others. For example, a chrome extension that receives eth funds, crafts a purchase transaction, but gives the tokens to the original sender of funds. 
This is also needed for any other use-case where the one sending the money is not the one that should receive the tokens.
