### ISSUE TITLE
Use uint256 for timestamps

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/zeppelin-solidity#593]
As reported in #517, `TokenTimelock` uses `uint64` for its timestamp state variable.

As I explained elsewhere: `uint256` is the only integer size native to the EVM. For all other integer sizes, the Solidity compiler generates extra operations to e.g. truncate on overflow. Because of this, using uint64 doesn't really lead to smaller contracts or less gas costs.

We should be using `uint256` for consistency.

**Comment by EnchanterIO** [comment]
is this the reason why timestamp is represented as uint256 in EVM? because it's native? 

BTW it seems to me like an overkill for timestamp to be uint256. Do you know why EVM developers took such a decision?

**Comment by Shrugs** [comment]
uint256 is the native integer size, so any operations on integer sizes smaller require extra processing at runtime. it's not really a specific timestamp concern. and making it a uint256 simplifies the operations being performed on it
