### ISSUE TITLE
Burnable Token should be inherited from Basic Token

### ISSUE THREAD

**Issue by izetex** [OpenZeppelin/zeppelin-solidity#596]
There is no reason why Burnable token should be exactly Standard token

It adds dependency which is never used in Burnable token. I have an issue while designing a contract of token that can be burnt.

I propose to change Burnable token  to

contract BurnableToken is BasicToken {... }

**Comment by frangio** [comment]
Totally agree. Do you want to submit a PR to fix this @izetex?

**Comment by izetex** [comment]
Created pull request https://github.com/OpenZeppelin/zeppelin-solidity/pull/600

**Comment by AugustoL** [comment]
Issue fixed, closing it.
