### ISSUE TITLE
ERC20 StandardToken approve front-running attack

### ISSUE THREAD

**Issue by hayeah** [OpenZeppelin/zeppelin-solidity#599]
The standard recommendation to prevent front-running `approve` is to set it to 0, then set it to the new value.

According to the original reporter of this vulnerability, this is not enough, because the attacker could still front-run the transaction that sets the approval value to 0.

Some sort of compare-and-set is required to patch this problem properly.

* * *

One backward compatible hack to solve this problem is to allowthe approved `_value` argument to be negative. If `_value` is negative, consider it a decrement to the approval value.

To safely set the approved value to 0, the token holder should approve the negative value of the current known approved value. The transaction should fail if the resulting value is not zero (i.e. another transaction had modified the approval value).

But the ERC20 interface requires an uint256 value, the hack is to unsafely cast that number to an int256... like so:

```
function approve(address _spender, uint256 _value) public returns (bool success) {
  int256 signedValue = int256(_value);
  if (signedValue < 0) {
    allowed[msg.sender][_spender] += signedValue;
    require(allowed[msg.sender][_spender] == 0);
    return true;
  }
  allowed[msg.sender][_spender] = _value;
  Approval(msg.sender, _spender, _value);
  return true;
}
```

Not sure if this "fix" is more evil than the problem itself. Thoughts?

**Comment by frangio** [comment]
Thanks for the suggestion @hayeah!

Sadly, casting a `uint256` to `int256` renders it non backwards compatible.

There are already alternatives to `approve` in OpenZeppelin's `StandardToken` meant to mitigate the front-running attack.
https://github.com/OpenZeppelin/zeppelin-solidity/blob/83b941c76cb08b7c95b45fd046116e7a70d72a1f/contracts/token/StandardToken.sol#L76-L85
However this is still vulnerable as you pointed out and as discussed in #437.

I am beginning to think that `decreaseApproval` should fail as proposed in #437, similar to the functionality you described for `approve`.

Closing this issue to continue the discussion there.
