### ISSUE TITLE
Does StandardToken.sol really comply with the ERC20 standard?

### ISSUE THREAD

**Issue by AxiomFlow** [OpenZeppelin/zeppelin-solidity#618]
The ERC20 standard mentions a `transfer` function, which is missing in `StandardToken.sol`.

**Comment by boutdemousse** [comment]
It looks like you may have [missed this part](https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/token/StandardToken.sol#L15) :   
````
contract StandardToken is ERC20, BasicToken 
````
If you run a test using `transfer` using StandardToken.sol you will see that there is no problem.
