### ISSUE TITLE
Use MintableToken and BurnableToken in same Crowdsale Contract

### ISSUE THREAD

**Issue by thomsonimjd** [OpenZeppelin/zeppelin-solidity#619]
In cases, I have to use the Mintable and Burnable  concepts for a token, where It's not possible to use the MintableTokena.sol and the BurnabelToken.sol in a crowdsale.  Could you please let me know what are the posibilities to work on this?. It would be better if there is any samples on this situation.

**Comment by Shrugs** [comment]
You can make a token that is both `Mintable` and `Burnable`, no problem with that. From there, you'll have to modify the `Crowdsale` contract to accept your `MintableAndBurnable` token signature that you created, since it currently only accepts `MintableToken` types.
