### ISSUE TITLE
Typo in TokenDestructible test file

### ISSUE THREAD

**Issue by Milkho** [OpenZeppelin/zeppelin-solidity#630]
https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/test/TokenDestructible.test.js#L10
**fron** instead of **from**

**Comment by Shrugs** [comment]
Nice catch! I've fixed it in https://github.com/OpenZeppelin/zeppelin-solidity/pull/634

**Comment by spalladino** [comment]
Fixed, thanks for the report @Milkho!
