### ISSUE TITLE
duplicate labels

### ISSUE THREAD

**Issue by ajsantander** [OpenZeppelin/zeppelin-solidity#637]
The issue tracker currently has duplicate labels, for example:
- review
- pending review
- under review

**Comment by federicobond** [comment]
I suggest we consolidate all of them under `pending review`.

**Comment by eordano** [comment]
I'd suggest keeping `pending-review`, `under-review` and change `feedback` for `has-feedback`

**Comment by ajsantander** [comment]
Will address this with the maintainers.
