### ISSUE TITLE
Possible critical bug in ECRecovery

### ISSUE THREAD

**Issue by sullof** [OpenZeppelin/zeppelin-solidity#644]
I am building a contract which checks the signer of a certain message.
For my tests I signed the string `sullof` using MyEtherWallet and Metamask at ([https://www.myetherwallet.com/signmsg.html](https://www.myetherwallet.com/signmsg.html)). 
The result is:
```
{
      "address": "0x41bdd852d3618dc5d6338279f373bf7935dc0242",
        "msg": "sullof",
        "sig": "0x335473213ac39fb66c74e8b23523583544389eef70e8bce4cc455cb41662083b1fe6981161e68c29e25fe65fb40f49f2c8adecfb0a1eda8d1c55a0c127e50cb01c",
        "version": "2"
    }
```
Unfortunately `ECRecovery.recover` returns the wrong address.

I added the following test to ECRecovery.test.js:
```
it('recover signer', async function () {
    // Signature generated outside testrpc with MyEtherWallet and Metamask

    let signer = '0x41bdd852d3618dc5d6338279f373bf7935dc0242';

    let message = '0x47c322ba85ab101b25573c9262d399b6e619f434298f6c1e593d2612a935264c';

    assert.equal(web3.sha3('sullof'), message);

    // eslint-disable-next-line max-len
    let signature = '0x335473213ac39fb66c74e8b23523583544389eef70e8bce4cc455cb41662083b1fe6981161e68c29e25fe65fb40f49f2c8adecfb0a1eda8d1c55a0c127e50cb01c';
    assert.equal(signer, await ecrecovery.recover(message, signature));

  });
```
It fails with the error
```
1) Contract: ECRecovery recover signer:
     AssertionError: expected '0x41bdd852d3618dc5d6338279f373bf7935dc0242' 
     to equal '0x730720a38c98b59be484b1021e350c3183696c93'
```
To be sure that it was not a problem with Metamask, I exported my private key and I tried directly inside MyEtherWallet and the signature is definitely correct.

Any idea?

PS > You can check the added test at [https://github.com/sullof/zeppelin-solidity/blob/testing-RCRecovery/test/ECRecovery.test.js](https://github.com/sullof/zeppelin-solidity/blob/testing-RCRecovery/test/ECRecovery.test.js)

**Comment by AugustoL** [comment]
Hello @sullof I think the function that uses testrpc to sign messages is different to the one used by metamask and myetherwallet, that should be why you test is failing, check the https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/test/helpers/hashMessage.js file

testrpc adds a prefix to the message that will be signed, I think myEtherWallet and Metamask dont.

**Comment by frangio** [comment]
Agree with @AugustoL.

Testrpc is using [`eth_sign`](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_sign) which prefixes the signed message for security reasons. And from https://github.com/ethereum/go-ethereum/issues/14794#issuecomment-314815863:
>It seems that MyEtherWallet and Etherscan.io do not use prefixes at all

Please reopen if this is not the cause of the problem!

**Comment by sullof** [comment]
Thanks. Actually, that is what I was thinking.

**Comment by sullof** [comment]
@AugustoL I verified and it works. But in a real scenario I have a contract which has to verify a signature generated by Metamask or MEW or whatever. I guess that I should check the two cases, with or without prefix. But anyway, I have to do the check in the contract, and there that helper is useless.
What I am saying is that ECRecovery is nice but is not enough because is basically applicable only when I have everything in the expected format. But if my contract receive it from outside and I have to format the message within the contract, it would be very useful to have a contract ECRecover with some additional function, instead of the library ECRecovery. 
What do you think?

**Comment by sullof** [comment]
BTW, I added two more tests. The first using `hashMessage` and it fails, the second building the message myself [https://github.com/sullof/zeppelin-solidity/blob/testing-RCRecovery/test/ECRecovery.test.js](https://github.com/sullof/zeppelin-solidity/blob/testing-RCRecovery/test/ECRecovery.test.js).
```
it('should recover signer but fails', async function () {
    // Signature generated outside testrpc with MyEtherWallet and Metamask

    let signer = '0x41bdd852d3618dc5d6338279f373bf7935dc0242';

    let baseMessage = 'sullof';

    let message = hashMessage(baseMessage);


    // eslint-disable-next-line max-len
    let signature = '0x335473213ac39fb66c74e8b23523583544389eef70e8bce4cc455cb41662083b1fe6981161e68c29e25fe65fb40f49f2c8adecfb0a1eda8d1c55a0c127e50cb01c';

    assert.notEqual(signer, await ecrecovery.recover(message, signature));

  });

  it('recover signer', async function () {
    // Signature generated outside testrpc with MyEtherWallet and Metamask

    let signer = '0x41bdd852d3618dc5d6338279f373bf7935dc0242';

    let baseMessage = 'sullof';

    let fullMessage = `\x19Ethereum Signed Message:\n${baseMessage.length}${baseMessage}`

    let message = web3.sha3(fullMessage)

    // eslint-disable-next-line max-len
    let signature = '0x335473213ac39fb66c74e8b23523583544389eef70e8bce4cc455cb41662083b1fe6981161e68c29e25fe65fb40f49f2c8adecfb0a1eda8d1c55a0c127e50cb01c';
    
    assert.equal(signer, await ecrecovery.recover(message, signature));

  });
```
The second works. This means that in any case `hashMessage` does not implement that in the way MEW and Metamask do. 

I think that, since the most common use is that people will sign messages with Metamask or MyEtherWallet, you could add specific tests to verify signatures produces by them. In any case, that is not very useful because the smart contract will have to do the job and it would be better to have a powerful smart contract that someone can extend which offers all the necessary helpers.

**Comment by sullof** [comment]
@frangio The problem was quite the opposite. In fact adding the prefix it works, see above. But I don't understand how the test at [https://github.com/sullof/ethereumjs-util/blob/master/index.js#L359](https://github.com/sullof/ethereumjs-util/blob/master/index.js#L359) can work, since it does a simple `web3.sha3('OpenZeppelin')`.
Actually, my first test was a duplicate of that one, and this is why it was failing.

**Comment by sullof** [comment]
MyEtherWallet for sure prefixes the message (the way I did) because it uses `hashPersonalMessage` from `ethereymjs-util` for that.

[https://github.com/kvhnuke/etherwallet/blob/mercury/app/scripts/controllers/signMsgCtrl.js#L80](https://github.com/kvhnuke/etherwallet/blob/mercury/app/scripts/controllers/signMsgCtrl.js#L80)

[https://github.com/sullof/ethereumjs-util/blob/master/index.js#L359](https://github.com/sullof/ethereumjs-util/blob/master/index.js#L359)

**Comment by AugustoL** [comment]
@sullof I dont understand where is the problem, I used this library successfully with the `eth-utils` libs that uses secp256k1 for signatures.

Please check the tests of LifChannels contracts that I did, it is a simple implementation of state channels for a ERC20 token, it uses the ECRecovery library.

https://github.com/windingtree/LifToken/blob/master/test/LifChannels.js

https://github.com/windingtree/LifToken/blob/master/contracts/LifChannels.sol

ecsign function used in the tests:
https://github.com/ethereumjs/ethereumjs-util/blob/0bc0616c2de0de0723f87c3b64923bb9f962a8e1/index.js#L339-L347

It does not matter what you use to generate the signature, if you add a prefix or not, the signer is recovered successfully if you provide the right hash of the message signed.

I hope the LifChannels test and contract helps.

**Comment by sullof** [comment]
> It does not matter what you use to generate the signature, if you add a prefix or not, the signer is recovered successfully if you provide the right hash of the message signed.

Of course, but here I am talking about how the original message is formatted, before hashing it. The [two tests that I added to ECRecovery.test.js in my fork](https://github.com/sullof/zeppelin-solidity/blob/testing-RCRecovery/test/ECRecovery.test.js) show the problem.

Anyway, I will take a look at LifChannels. Thanks.

**Comment by passionofvc** [comment]
hit @sullof 
I found why it not work with from MyEtherWallet signature,
your hashMessage method hash message with sha3,
but[hashPersonalMessage]( https://github.com/ethereumjs/ethereumjs-util/blob/54aa41ccb5c09de626ee358499e2efab535bc0bf/index.js#L373-376
) directly convert to byte buffer, just not hash, so it can not verify.
use hashPersonalMessage it work fine I tested it.

[ECRecovery.test.js](https://github.com/passionofvc/blockchain-passion.github.io/blob/master/eth/eth-debug-SC/test/ECRecovery.test.js
)


```
   it('should recover signer but fails', async function () {
     // Signature generated outside testrpc with MyEtherWallet and Metamask
 
     let signer = '0x41BDD852d3618Dc5D6338279F373Bf7935dc0242';
 
     let baseMessage = 'sullof';
     const messageHex =ethUtils.sha3(baseMessage).toString('hex');
 
     //let message = hashMessage(baseMessage);
     let message = ethUtils.hashPersonalMessage( ethUtils.toBuffer(baseMessage) );
     message = ethUtils.bufferToHex(message)
 
     console.log(messageHex, message)
     // eslint-disable-next-line max-len
     let signature =                                                                                                                     '0x335473213ac39fb66c74e8b23523583544389eef70e8bce4cc455cb41662083b1fe6981161e68c29e25fe65fb40f49f2c8adecfb0a1eda8d1c55a0c127e50cb01c';
     var address = await ecrecovery.recover(message, signature)
     console.log(signer, address )
     //assert.notEqual(signer, address)
     assert.equal(signer, address)
 
   });
```
