### ISSUE TITLE
Split Payment

### ISSUE THREAD

**Issue by Jasintar** [OpenZeppelin/zeppelin-solidity#652]
Please help!
How to use SplitPayment contract in Crowdsale contract?
Token has balances as a mapping (address => uint256), but SplitPayment constructor requires two arrays address and uint256 separately.

**Comment by GULSHAN-VASNANI** [comment]
Which all addresses you require for SplitPayment array ?

**Comment by frangio** [comment]
Hi @Jasintar. Please note that `SplitPayment` only works to split _ether_ payments, and not tokens, at the moment.

What is it you're trying to do?

**Comment by Shrugs** [comment]
The comments within the contract as well as the tests should provide ample example usage; do you have a specific question?
