### ISSUE TITLE
Transfer method to block until ICO ends

### ISSUE THREAD

**Issue by thomsonimjd** [OpenZeppelin/zeppelin-solidity#653]
Hi,

I would like to know how to disable transfer token method for a user to send their tokens to other untill the ICO ends.  This is possible when I do make the ICO without zappelin.  I would like to use the Open Zeppelin with my ICO, whereas it  is not possible to make.  Could you please guid me on this?

Regards,
Thomson I.

**Comment by grimsa** [comment]
This should be simple:
1. Token should extend `Pausable` and override both transfer methods to add modifier `whenNotPaused`.
2. ICO should then call `pause` right after token is created and implement `FinalizableCrowdsale` to `unpause` on finalization.

**Comment by frangio** [comment]
@grimsa's suggestion is spot on, except I would recommend using [`PausableToken`](https://github.com/OpenZeppelin/zeppelin-solidity/blob/v1.5.0/contracts/token/PausableToken.sol).
