### ISSUE TITLE
Pausable and Burnable  

### ISSUE THREAD

**Issue by thomsonimjd** [OpenZeppelin/zeppelin-solidity#657]
Hi,

Could you please let me know how to use Burnable and Pausable contracts together in open zeppelin in hand in hand.  It would be bette if you could give me any samples on this case.  I have not come accross this scenario yet.  Thanks in advance.

**Comment by frangio** [comment]
Hi @thomsonimjd. If you want to create a token that is Burnable as well as Pausable you can do that in the following way:
```
contract MyToken is PausableToken, BurnableToken {
}
```

Your question is somewhat broad, however. Consider asking for help over in the #beginners channel of our [OpenZeppelin Slack community](https://slack.openzeppelin.org/).
