### ISSUE TITLE
SimpleToken has to emit a Transfer event in the constructor to be ERC20 compliant

### ISSUE THREAD

**Issue by facuspagnuolo** [OpenZeppelin/zeppelin-solidity#659]
[x] 🐛 This is a bug report.

The [ERC20 standard](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-20-token-standard.md#transfer-1) describes that a token contract should trigger a Transfer event with the _from address set to 0x0 when tokens are created. SimpleToken should trigger a Transfer event then.

**Comment by frangio** [comment]
Fixed by #660.
