### ISSUE TITLE
Condition Oriented Programming?

### ISSUE THREAD

**Issue by se3000** [OpenZeppelin/zeppelin-solidity#66]
Do you all have any thoughts on [Condition Oriented Programming](https://blog.ethcore.io/condition-oriented-programming-2/)? I've seen a couple places where branching logic is in the methods, most often something like `if (foo) throw;`. Which still seems like it could be pulled out into modifiers. Does Zeppelin have any stance on this pattern? 

It definitely requires more code, and could be more expensive. But on the positive side, there is cleaner separation of concerns, limited complexity, and I think the expressiveness that comes with naming modifiers is very valuable.

**Comment by maraoz** [comment]
Oh! Interesting concept. Still not convinced we want this, but I'll post it on slack to receive more feedback and thoughts from the community. Thanks for sharing!
