### ISSUE TITLE
Token Lock

### ISSUE THREAD

**Issue by elango501** [OpenZeppelin/zeppelin-solidity#662]
## The Problem

- [ ] 🐛 This is a bug report.
- [ ] 📈 This is a feature request.

Briefly describe the issue you are experiencing (or the feature you want to see added to OpenZeppelin). Tell us what you were trying to do and what happened instead. **Remember, this is _not_ a place to ask for help debugging code; for that, we welcome you in the [OpenZeppelin Slack Channel](https://slack.openzeppelin.org/).**

## 💻 Environment

First, we need to know what your environment looks like.

- Which version of OpenZeppelin are you using?
- What network are you deploying to? testrpc? Ganache? Ropsten?
- How are you deploying your OpenZeppelin-backed contracts? truffle? Remix? Let us know!

## 📝 Details

Describe the problem you have been experiencing in more detail. Include as much information as you think is relevant. Keep in mind that transactions can fail for many reasons; context is key here.

## 🔢 Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

```
insert short code snippets here
```

**Comment by facuspagnuolo** [comment]
@elango501 would you mind describing the issue please?

**Comment by spalladino** [comment]
Closing
