### ISSUE TITLE
Some tests are failing intermittently.

### ISSUE THREAD

**Issue by TimTinkers** [OpenZeppelin/zeppelin-solidity#670]
## The Problem

- [X] 🐛 This is a bug report.

I have cloned the master repository and am attempting to verify that the tests are working before I try using any of the provided contracts. The tests are failing intermittently. Here's a [gist containing my logs demonstrating this](https://gist.github.com/TimTinkers/f98cba449b43e3099420150cbb6977d0). The tests should behave consistently across truffle runs. If they don't, how can they be trusted as unit tests?

## 💻 Environment

First, we need to know what your environment looks like.

- I am using a clone of the OpenZeppelin master at commit `9469772`.
- I am testing locally with ganache-cli v6.0.3 using the following script to launch:
```
ganache-cli --account="0x2bdd21761a483f71054e14f5b827213567971c676928d9a1808cbfa4b7501200,1000000000000000000000000" --account="0x2bdd21761a483f71054e14f5b827213567971c676928d9a1808cbfa4b7501201,1000000000000000000000000" --account="0x2bdd21761a483f71054e14f5b827213567971c676928d9a1808cbfa4b7501202,1000000000000000000000000" --account="0x2bdd21761a483f71054e14f5b827213567971c676928d9a1808cbfa4b7501203,1000000000000000000000000" --account="0x2bdd21761a483f71054e14f5b827213567971c676928d9a1808cbfa4b7501204,1000000000000000000000000" --account="0x2bdd21761a483f71054e14f5b827213567971c676928d9a1808cbfa4b7501205,1000000000000000000000000" --account="0x2bdd21761a483f71054e14f5b827213567971c676928d9a1808cbfa4b7501206,1000000000000000000000000" --account="0x2bdd21761a483f71054e14f5b827213567971c676928d9a1808cbfa4b7501207,1000000000000000000000000" --account="0x2bdd21761a483f71054e14f5b827213567971c676928d9a1808cbfa4b7501208,1000000000000000000000000" --account="0x2bdd21761a483f71054e14f5b827213567971c676928d9a1808cbfa4b7501209,1000000000000000000000000"
```
- I am deploying using truffle, version 4.0.4.

## 🔢 Code To Reproduce Issue

To reproduce this issue it should be sufficient to download the repository like I did, setup the ganache-cli environment like I did, and then keep running `truffle test` until failures/differences between runs is observed.

## 👍 Other Information

There are some similar issues that were closed by truffle in the past, but none of those solutions seem to apply to fix the situation here. Any help?
https://github.com/trufflesuite/truffle/issues/557
https://github.com/trufflesuite/ganache-cli/issues/35
https://github.com/trufflesuite/truffle/issues/614

**Comment by frangio** [comment]
Hi @TimTinkers, thanks for reporting.

We've been aware of this issue for a while but thought it was a Truffle problem. Although I think Truffle is failing to report the error correctly, I'm beginning to think that there's an error on our side that is causing it. I'm going to be looking at it.

Please note, though, that it's not that the tests are failing intermittently, but that sometimes they _crash_. When they don't crash, they consistently pass.
