### ISSUE TITLE
No documentation for Crowdsale smart contract and derivatives.

### ISSUE THREAD

**Issue by anaibol** [OpenZeppelin/zeppelin-solidity#697]
![screenshot_20180122_104224](https://user-images.githubusercontent.com/3210177/35214409-5853dc82-ff61-11e7-82b1-0bfc7cafa2a9.png)

**Comment by frangio** [comment]
Thanks for reporting @anaibol. Documentation is being worked on, and we'll be releasing a new site soon. In the meantime please refert to the contracts' comments in the source code.

Closing in favor of #594.
