### ISSUE TITLE
SplitPayments not splitting payments correctly

### ISSUE THREAD

**Issue by rmujica** [OpenZeppelin/zeppelin-solidity#716]
## 🎉 Description
When running a contract inheriting SplitPayment, some claims being made with the same amount of shares are different by 1.5e15 wei, while other claims being made with the same amount of shares (but smaller than the previous by an order of magnitude) are the same.

- [x] 🐛 This is a bug report.
- [ ] 📈 This is a feature request.

## 💻 Environment

Next, we need to know what your environment looks like.

- Which version of OpenZeppelin are you using? 1.6.0 installed via NPM
- What network are you deploying to? testrpc? Ganache? Ropsten? Ganache, 11 account setup
- How are you deploying your OpenZeppelin-backed contracts? truffle? Remix? Let us know! truffle.

## 📝 Details

As told in the description. When instancing the contract, 9 payees are added with the following share structure:
payees 1 and 2: 14 shares
payees 3 through 9: 1 share

A test is run transfering 1 Ethereum to the contract, then payees 1 through 9 claim in order.

Expected behaviour: payees 1 and 2 claim 0.4 Ethereum, payees 3 through 9 claim 0.0285714 Ethereum. payees 1 and 2 should claim the same amount, payees 3 through 9 claim the same amount.

Observed behaviour: payee 1 claims 0.39272 Ethereum, payee 2 claims 0.39422 Ethereum, payees 3 through 9 claim 0.022801 Ethereum. payee 1 and payee 2 claims are different, but payees 3 through 9 effectively claim the same (erroneous) amount.

## 🔢 Code To Reproduce Issue [ Good To Have ]

In order to make it easier to reproduce, I made a test case against the production OpenZeppelin library that is currently failing (basically the same test on the OpenZeppelin repo but with other payee-share structure).

https://gist.github.com/rmujica/71b0e5ce92e9d8e347e3093326b9d838

## 👍 Other Information

Discussed on slack: https://openzeppelin.slack.com/archives/C4GP7FGM7/p1517423076000499

**Comment by rmujica** [comment]
pinging @Shrugs

**Comment by Shrugs** [comment]
Figured it out!

The first call to `claim()` requires `72461` gas whereas subsequent calls require `57461` gas. I expect this is probably due to some allocation issue that I don't have the experience to know right away.

Anyway, the payees are _claiming_ the correct amount, but _spending_ different amounts executing the transaction that claims them. That's why the resulting balances don't add up.

If you include the gas price in your calculations, I expect the numbers will add up without the `< 1e16` part.

**Comment by Shrugs** [comment]
Also, best practices, try to use the bignumber math function when working with wei and whatnot; you never know where you're accidentally rounding something

**Comment by Shrugs** [comment]
And there's still 3 wei left over in the account because of rounding against `1/35`. if you take `.028571429` times `7` you get `.200000003`, hence the leftover amount.

**Comment by rmujica** [comment]
perfect, thanks a lot.
