### ISSUE TITLE
npm not aligned with github

### ISSUE THREAD

**Issue by ddbit** [OpenZeppelin/zeppelin-solidity#719]
## 🎉 Description

The Crowdsale.sol constructor declares argument token in 1.6.0 on github but npm installs a code without that argument.

- [x] 🐛 This is a bug report.
- [ ] 📈 This is a feature request.

## 💻 Environment

Next, we need to know what your environment looks like.

- Which version of OpenZeppelin are you using? 1.6.0
- What network are you deploying to? testrpc? Ganache? Ropsten? n/a
- How are you deploying your OpenZeppelin-backed contracts? truffle? Remix? Let us know!
N/A
## 📝 Details
token argument is just missing in the npm installed code.

## 🔢 Code To Reproduce Issue [ Good To Have ]

```
mkdir InstallOZ
cd InstallOZ/
npm i zeppelin-solidity
cat node_modules/zeppelin-solidity/contracts/crowdsale/Crowdsale.sol | grep "function Crowdsale"
```
The output is a constructor without argument token

**Comment by BenKaufman10** [comment]
Happens to me too, any solution?

**Comment by facuspagnuolo** [comment]
Hi @ddbit! Thanks for reaching out
Would you mind providing a link to the documentation you are looking at? You can check that commit was not included in the release, please see the [diff](https://github.com/OpenZeppelin/zeppelin-solidity/commit/4d7c3cca7590e554b76f6d91cbaaae87a6a2e2e3) and the [released contract](https://github.com/OpenZeppelin/zeppelin-solidity/blob/v1.6.0/contracts/crowdsale/Crowdsale.sol#L44).

**Comment by dadaista** [comment]
Hi @facuspagnuolo, definitely my fault, I wrongly assumed the 1.6.0 was carrying this novelty but actually it is not. The master is some commits ahead. We can close the issues

**Comment by ddbit** [comment]
Hi @facuspagnuolo, definitely my fault, I wrongly assumed the 1.6.0 was carrying this novelty but actually it is not. The master is some commits ahead. We can close the issues
