### ISSUE TITLE
Mintable token shouldn't let the mint finish if the total supply is 0

### ISSUE THREAD

**Issue by eduardonunesp** [OpenZeppelin/zeppelin-solidity#721]
- [ ] 🐛 This is a bug report.
- [x] 📈 This is a feature request.

Mintable token shouldn't let the mint finish if the total supply is `0`, since the mintable once it's finished it cannot be minted again. It happens on `MintableToken.sol`

https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/token/ERC20/MintableToken.sol#L44

**Comment by federicobond** [comment]
Hi @eduardonunesp, thank you for your suggestion! I believe it should be up to the user to decide whether to finish the mint or not, regardless of how many tokens were minted. Checking for this condition would consume gas and provide no tangible business value.
