### ISSUE TITLE
Error encountered, bailing. Network state unknown. Review successful transactions manually. Error: VM Exception while processing transaction: revert

### ISSUE THREAD

**Issue by tonywangcn** [OpenZeppelin/zeppelin-solidity#722]
## 🎉 Description

- [* ] 🐛 This is a bug report.
- [ ] 📈 This is a feature request.

## 💻 Environment

Next, we need to know what your environment looks like.

- Which version of OpenZeppelin are you using? v1.6.0
- What network are you deploying to? testrpc? Ganache? Ropsten? testrpc
- How are you deploying your OpenZeppelin-backed contracts? truffle? Remix? Let us know! truffle

## 📝 Details

Describe the problem you have been experiencing in more detail. Include as much information as you think is relevant. Keep in mind that transactions can fail for many reasons; context is key here.

Error after running cmd below:
truffle migrate --network development

```
Using network 'development'.

Running migration: 2_deploy_contracts.js
1520374082 1522102082 1000 '4000000000000000000000' '0x4b7bebc60d1308b3f1bb15de43e373aecff81092'
  Deploying LUXCoinCrowdsale...
  ... 0x207f8d7293e801e139d01789fa9d9877335335ddb021adc3859f19d73dc9b904
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: VM Exception while processing transaction: revert
    at Object.InvalidResponse (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:41483:16)
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:330353:36
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:176198:11
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:326008:9
    at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:329052:7)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:176427:18)
    at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:176717:12)
    at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:176872:12)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:176832:24)
    at emitNone (events.js:111:20)
```

## 🔢 Code To Reproduce Issue [ Good To Have ]

Contract for tokencrowdsale:

https://github.com/tonywangcn/ContractForLUX/blob/master/contracts/LUXCoinCrowdsale.sol
```
pragma solidity ^0.4.17;

import './LUXCoin.sol';
import "./CappedCrowdsale.sol";

contract LUXCoinCrowdsale is CappedCrowdsale {
  function LUXCoinCrowdsale(uint256 _startTime, uint256 _endTime, uint256 _rate, uint256 _cap, address _wallet, MintableToken _token) public 
    CappedCrowdsale(_cap)
    Crowdsale(_startTime, _endTime, _rate, _wallet, _token)
  {
  }
  function createTokenContract() internal returns (MintableToken) {
    return new LUXCoin();
  }
}
```
truffle.js configuration

```
module.exports = {
  // See <http://truffleframework.com/docs/advanced/configuration>
  // to customize your Truffle configuration!
  networks: {
    development: {
      network_id: "*",
      host: "127.0.0.1",
      port: 8545,   // Different than the default below
      gas: 6712388,
      gasPrice: 65000000000,
    }
  },
  rpc: {
    host: "127.0.0.1",
    port: 8545
  },
  solc: {
    optimizer: {
      enabled: true,
      runs: 200
    }
  }

};
```

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

```
insert short code snippets here
```

## 👍 Other Information
Details for this error:
Stackoverflow link : https://ethereum.stackexchange.com/questions/38539/error-encountered-bailing-network-state-unknown-review-successful-transaction

**Comment by federicobond** [comment]
Hi @tonywangcn! The error messages says "VM Exception while processing transaction: revert". This usually means a `require` clause did not succeed. Please check every argument you are providing to the contract constructor to make sure they are valid.

If the problem persists, please include a failing test case in your report.
