### ISSUE TITLE
BurnableToken doesn't fire Transfer event

### ISSUE THREAD

**Issue by rstormsf** [OpenZeppelin/zeppelin-solidity#732]
- [x] 📈 This is a feature request.
## 🎉 Description
As a user, I'd expect that BurnableToken when called `burn(uint _value)` method, it should fire 
`Transfer(msg.sender, address(0), value);` event. 

https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/token/ERC20/BurnableToken.sol#L18

the same as MintableToken does when it fires `mint(to, value)`
https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/token/ERC20/MintableToken.sol#L35
```
    Transfer(address(0), _to, _amount);
```

Thoughts?

**Comment by androolloyd** [comment]
Is it a transfer though, it reads to me as a complete destruction of the burned token, rather than movement of it to a null location.

**Comment by AugustoL** [comment]
I think it should have it! we had to change the burn method in the LifToken implementation to add the burn function.

**Comment by AugustoL** [comment]
@rstormsf can you go ahead and create the PR? assign me as reviewer pls.

**Comment by rstormsf** [comment]
@AugustoL done
