### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by freshonline** [OpenZeppelin/zeppelin-solidity#736]
testnet@e3:~$ npm install zeppelin-solidity
npm WARN saveError ENOENT: no such file or directory, open '/home/testnet/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/testnet/package.json'
npm WARN testnet No description
npm WARN testnet No repository field.
npm WARN testnet No README data
npm WARN testnet No license field.

+ zeppelin-solidity@1.6.0
added 8 packages in 1.735s
testnet@e3:~$

**Comment by spalladino** [comment]
The problem seems to be that you have not initialized your project with `npm init`. It's a problem related to npm usage, not to OpenZeppelin, so I'm closing the issue. For future reference, please ask these questions on the beginners channel in [Slack](http://slack.openzeppelin.org/).
