### ISSUE TITLE
Test helpers reusability issue

### ISSUE THREAD

**Issue by avadaneidanut** [OpenZeppelin/zeppelin-solidity#740]
## 🎉 Description

I try to reuse the helper functions from test/helpers (which are great by the way) and for some of them (the ones that use ES6 syntax) fail beautifully.

## 💻 Environment

I use:
- zeppelin-solidity v1.6.0
- node v9.5.0
- truffle v4.0.6

I register babel dependencies in truffle-config.js.

## 📝 Details

Pieces of code that work as expected:
```js
import assertJump from 'zeppelin-solidity/test/helpers/assertJump';
import expectEvent from 'zeppelin-solidity/test/helpers/expectEvent';
import transactionMined from 'zeppelin-solidity/test/helpers/transactionMined';
```

Pieces of code that fail:
```js
import assertRevert from 'zeppelin-solidity/test/helpers/assertRevert';
import decodeLogs from 'zeppelin-solidity/test/helpers/decodeLogs';
import hashMessage from 'zeppelin-solidity/test/helpers/hashMessage';
```
or
```js
const assertRevert = require('zeppelin-solidity/test/helpers/assertRevert');
const decodeLogs = require('zeppelin-solidity/test/helpers/decodeLogs');
const hashMessage = require('zeppelin-solidity/test/helpers/hashMessage');
```

Both formats throw the same exception:
```
home/danut/testing/node_modules/zeppelin-solidity/test/helpers/decodeLogs.js:3
export default function decodeLogs (logs, contract, address) {
^^^^^^

SyntaxError: Unexpected token export
    at new Script (vm.js:51:7)
    at createScript (vm.js:138:10)
    at Object.runInThisContext (vm.js:199:10)
    at Module._compile (module.js:624:28)
    at Module._extensions..js (module.js:671:10)
    at Object.require.extensions.(anonymous function) [as .js] (home/danut/testing/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
```

I'll appreciate any idea on how to fix this because I am required to copy the files into my project's test/helpers directory which is a workaround. After I copy them I can do
```js
import assertRevert from './helpers/assertRevert';
```
without any problems.

**Comment by spalladino** [comment]
As far as I understand, the issue is that Babel does not parse `node_modules` by default, so if we want to make test helpers available, we'd need to preprocess them before publishing the package.

As a workaround, you should be able to instruct Babel to parse the test helpers from Zeppelin (see [here](https://github.com/webpack/webpack/issues/2031#issuecomment-183378107) for an example on how to do it on webpack). But we should modify the package mechanism. I think @martriay had been looking into this some time ago...?

**Comment by avadaneidanut** [comment]
@spalladino I don't seem to understand how to do it. Where should I add the instructions for Babel?

**Comment by avadaneidanut** [comment]
@spalladino Thanks for the hints.

I've added this to the `truffle-config.js` file and it did the trick.
```js
require('babel-register')({
  ignore: /node_modules\/(?!zeppelin-solidity\/test\/helpers)/
});
```
And the `truffle-config.js` file now looks like:
```js
require('babel-register')({
  ignore: /node_modules\/(?!zeppelin-solidity\/test\/helpers)/
});
require('babel-polyfill');

module.exports = {
  // networks
};
```

**Comment by spalladino** [comment]
Good to hear!

**Comment by avadaneidanut** [comment]
@spalladino Maybe it will be nice to be a separated package for testing. I could benefit from that and I think a lot of people will.

**Comment by spalladino** [comment]
Indeed. It is being discussed in issue #326, though it has become somewhat
inactive.
