### ISSUE TITLE
Use #841 reference implementation in OpenZeppelin

### ISSUE THREAD

**Issue by fulldecent** [OpenZeppelin/zeppelin-solidity#745]
Presently, OpenZeppelin has ERC-721 (draft) implemented here https://github.com/OpenZeppelin/zeppelin-solidity/tree/master/contracts/token/ERC721

A reference implementation has just been released and added to the standard (draft). The reference is here: https://github.com/nastassiasachs/ERC721ExampleDeed

Could the reference implementation please be added to OpenZeppelin.

Also, please note, we prefer the name DEED, currently it is listed as a TOKEN. We would appreciate that for consistency a new DEED folder could be created.

Ping @nastassiasachs

**Comment by nastassiasachs** [comment]
I'm trying to contribute. Maybe someone can review this pull request: https://github.com/OpenZeppelin/zeppelin-solidity/pull/747

**Comment by fulldecent** [comment]
If there is any question as to whether 841 is the canonical standard for ERC-721 then please see the new comment at the top of the ERC-721 issue at https://github.com/ethereum/eips/issues/721

**Comment by fulldecent** [comment]
Pinging @facuspagnuolo @frangio to please review this request.

**Comment by spalladino** [comment]
Should be covered by #803
