### ISSUE TITLE
is there any example for crowdsale of non-mintabletoken?

### ISSUE THREAD

**Issue by leochan007** [OpenZeppelin/zeppelin-solidity#791]
in the example, it use MintableToken.
but i wanna use a standardtoken.

**Comment by Shrugs** [comment]
Use an [AllowanceCrowdsale](https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/crowdsale/emission/AllowanceCrowdsale.sol) and allow the crowdsale to transfer `_amount` of tokens. or use a normal [Crowdsale](https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/crowdsale/Crowdsale.sol) and `transfer()` some tokens to the crowdsale in your deploy script like

```
myToken.transfer(MyCrowdsale.address, _amount);
```

---

Also, please join us in the [slack channel](https://slack.openzeppelin.org/) for questions like these :)
