### ISSUE TITLE
`emit` in contract events for compatibility with solidity v0.4.21

### ISSUE THREAD

**Issue by Aniket-Engg** [OpenZeppelin/zeppelin-solidity#807]
## 🎉 Description

As recent release of solidity has been introduced 'emit' keyword to use with events to differentiate them from functions. This will be great if contracts of repository are updated so that they can be used with latest solidity compiler.

- [ ] 🐛 This is a bug report.
- [x] 📈 This is a feature request.

## 💻 Environment

This upgrade will help to run the contract with latest solc compiler.

**Comment by Shrugs** [comment]
Seems like a reasonable task for an "update to 0.4.21" pull request, once 0.4.21 has been in the wild for a bit

**Comment by Idiotcards** [comment]
The responsiveness to core updates reflects well on the community. Great work people.

**Comment by aleybovich** [comment]
@Shrugs do you have an ETA for this to be released? Thank you

**Comment by wildaces215** [comment]
I'll take a swing at it

**Comment by wildaces215** [comment]
Is this open?

**Comment by DumasV** [comment]
It depends on what is expected from this PR (#863). Because it only fixes part of the compiler warnings from the new soidity compiler.

**Comment by icole** [comment]
This can probably be closed with the improvements here https://github.com/OpenZeppelin/zeppelin-solidity/pull/876

**Comment by Shrugs** [comment]
thanks @icole! I had forgotten about this issue :)

**Comment by kirillDanshin** [comment]
when this fix will be released?

**Comment by Shrugs** [comment]
It will be published in version 1.9.0, currently scheduled for 1.5 weeks from now

**Comment by kirillDanshin** [comment]
how we can use this feature right now?

**Comment by Shrugs** [comment]
you can point your local project to the master branch of zeppelin-solidity

```
npm install git://github.com/OpenZeppelin/zeppelin-solidity.git#master --save
```

**Comment by jtakalai** [comment]
Why not bump minor version number for this? Warnings from a library are a silly thing, I'd love to get updates through npm proper...

**Comment by jtakalai** [comment]
aw shucks, that's no good, now I get the constructor() warnings. Hmmh.

**Comment by Shrugs** [comment]
`constructor()` warnings are due to the latest solidity version `0.4.22`.

**Comment by Aniket-Engg** [comment]
There were some bugs regarding constructor in `0.4.22`, use `0.4.23`
