### ISSUE TITLE
Update ERC721 to match spec

### ISSUE THREAD

**Issue by gakonst** [OpenZeppelin/zeppelin-solidity#809]
Now that the ERC721 NFT Standard has been merged (https://github.com/ethereum/EIPs/pull/841) and is now a [draft](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-721.md) standard, the ERC721 implementation at https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/token/ERC721/ERC721Token.sol should be updated

**Comment by spalladino** [comment]
See #803
