### ISSUE TITLE
How do I apply the MIT License to Open Zeppelin Code?

### ISSUE THREAD

**Issue by mudgen** [OpenZeppelin/zeppelin-solidity#810]
The source code provided by Open Zeppelin is under the MIT License.  If I include code from Open Zeppelin in my contract where/how should I include the MIT copyright notice and the permission notice?

**Comment by Shrugs** [comment]
Hi! the best resource I've found for learning about licenses is. TLDRLegal—here's the MIT license page! https://tldrlegal.com/license/mit-license

**Comment by mudgen** [comment]
So I just need to include the license text in any MIT licensed code I use?

**Comment by Shrugs** [comment]
> Basically, you can do whatever you want as long as you include the original copyright and license notice in any copy of the software/source.

yes
