### ISSUE TITLE
Add utility for data packing and bitshift/masking 

### ISSUE THREAD

**Issue by DanielRX** [OpenZeppelin/zeppelin-solidity#830]
## 🎉 Description

To help developers save money (and become more aware of storage costs) we should add and support (safe) bitshifts and utilities to store multiple types of data < 32bytes into one data slot 

- [ ] 🐛 This is a bug report.
- [x ] 📈 This is a feature request.

## 📝 Details

Adding 
`SafeShiftLeft`
`SafeShiftRight`
`PackData()` (overloaded with various options)
`UnpackData()`

Among others will allow users to pack many variables into one slot to save both gas for storage and with correct use, simplify code 

For example

```
  getTokenData1(uint256 tokenID) returns (uint8) 
    return tokens[tokenID].data1;
```

Can be generalised into 
```
     getTokenData(uint256 tokenID, uint256 indexOfData) returns (uint8)
    return mask(tokens[tokenID], MASKS[indexOfData]);

```
Where MASKs is a constant array of masks to allow for data to be masked out

**Comment by DanielRX** [comment]
I will be happy to supply a fair chunk of the code for this, but the safety checks I would need a few people to check over to make sure

**Comment by frangio** [comment]
Thanks for the suggestion @DanielRX! Solidity actually already packs contiguous small things into a single 256 bit word. It does this for struct members as well as state variables.

**Comment by DanielRX** [comment]
There have been many cases of structs not being stored in the EVM correctly as tight as they could but okay, Will just develop it alone and post it
