### ISSUE TITLE
Protect master branch from unsigned commits

### ISSUE THREAD

**Issue by eordano** [OpenZeppelin/zeppelin-solidity#837]
## 🎉 Description

Given how important this library is becoming for the ecosystem, all commits should be signed using GPG

- [x] 🐛 This is a bug report.
- [ ] 📈 This is a feature request.

## 👍 Other Information

https://help.github.com/articles/enabling-required-commit-signing/

**Comment by frangio** [comment]
I don't think we want to do this because it adds _a lot_ of overhead for contributors. Maybe it would be possible for maintainers to sign all squashed merge commits? I've been looking into it but I still don't understand if it would be possible to do that from GitHub's web interface.

**Comment by frangio** [comment]
What we can do, however, is sign all release commits. I don't think there's a way of enforcing this, though.

**Comment by eordano** [comment]
Sounds good and a great first step. I'm going to close this issue for the time being. More important things to discuss.
