### ISSUE TITLE
SafeMath.test.js Bug

### ISSUE THREAD

**Issue by barakman** [OpenZeppelin/zeppelin-solidity#854]
## 🎉 Description

Overflow tests are using integers which are way above Javascript's MAX_SAFE_INTEGER.

- [x] 🐛 This is a bug report.
- [ ] 📈 This is a feature request.

## 💻 Environment

Any platform.

## 📝 Details

In the overflow tests for SafeMath.sol, you are using integers which are way above Javascript's MAX_SAFE_INTEGER. Whether or not these tests work, I think is by mere coincidence (kind of *undefined behavior*, if this terminology applies for Javascript).

## 🔢 Code To Reproduce Issue

```
let x = 115792089237316195423570985008687907853269984665640564039457584007913129639935;
let y = 115792089237316195423570985008687907853269984665640564039457584007913129639936;
alert(x < y);
```

UPDATE:

In fact, this test passes by cheating.

It checks for `revert`, where the actual error to be expected is `invalid opcode`.
This is because the `SafeMath.sol` contract uses `assert`s rather than `require`s.

So the fix should include:

1. Replace each one of those large integers with `web3.toBigNumber("...")`.
2. Replace each `assertRevert` with `assertJump`.

Alternatively for the 1st bullet (a more appropriate fix IMO), you can simply use:

    let a = web3.toBigNumber(2).pow(256).minus(1)

BTW, I haven't been quite able to determine why a `revert` exception is thrown here to begin with.

---

Here is the exact fix that I have used:

```
  it('should throw an error on addition overflow', async function () {
    let a = web3.toBigNumber(2).pow(256).minus(1);
    let b = 1;
    try {
      await safeMath.add(a, b);
      assert.fail('should have thrown before');
    } catch (error) {
      assertJump(error);
    }
  });

  it('should throw an error on multiplication overflow', async function () {
    let a = web3.toBigNumber(2).pow(256).div(2);
    let b = 2;
    try {
      await safeMath.multiply(a, b);
      assert.fail('should have thrown before');
    } catch (error) {
      assertJump(error);
    }
  });
```

**Comment by frangio** [comment]
Related to #204.
