### ISSUE TITLE
Warnings for this.balance in contracts since 0.4.21

### ISSUE THREAD

**Issue by shyheim103** [OpenZeppelin/zeppelin-solidity#858]
## 🎉 Description

`wallet.transfer(this.balance);` throws a warning: "Using contract member "balance" inherited from the address type is deprecated. Convert the contract to "address" type to access the member."

- [x] 🐛 This is a bug report.
- [ ] 📈 This is a feature request.

**Comment by Shrugs** [comment]
The solution to this is probably to change line https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/crowdsale/distribution/utils/RefundVault.sol#L47 to

```
wallet.transfer(address(this).balance);
```

Because `.balance` is a property of the address type, not the Contract type.

**Comment by Shrugs** [comment]
@shyheim103 which compiler version are you using?

**Comment by frangio** [comment]
This warning is showing up since Solidity 0.4.21. It comes up in Travis after #876.

**Comment by shyheim103** [comment]
I solved it the way @Shrugs mentioned. It wasn't a problem for me, I was just informing the community about it in case someone else runs across it. Easy fix. But I was using compiler version 0.4.18 or 21
