### ISSUE TITLE
TokenVesting/Timelock with multiple beneficiaries

### ISSUE THREAD

**Issue by elie222** [OpenZeppelin/zeppelin-solidity#859]
TokenVesting and TokenTimelock allow for a single beneficiary each. It would be nice to have a single contract that could be used to vest multiple accounts.

Is there a reason this wasn't done in the already built Zeppelin contracts?
Are there any example crowdsales that offer this functionality that may be worth reading?

One way to use the current TokenVesting contract is to create a new contract for each account that needs to be vested. This is a little gas intensive and therefore expensive, but often this will be a minor issue in the case of ICOs. Is this the recommended way to use OpenZeppelin TokenVesting?

 📈 This is a feature request.

**Comment by elie222** [comment]
I see one example from Aragon that seems to be the kind of thing I'm looking for:
https://github.com/aragon/aragon-network-token/blob/master/contracts/MiniMeIrrevocableVestedToken.sol

**Comment by Shrugs** [comment]
Not sure why the decision was made, but it was probably due to "least concerns".

I expect you could compose the TokenVesting contract with a SplitPayment style contract to accomplish the same goal. The only difference is that the SplitPayment contract would have to "pull" the ether/tokens from the vesting contract before allowing beneficiaries to withdraw.

Any ideas on how that could be structured, without making backwards-incompatible changes to the existing TokenVesting/TokenTimelock contracts?

**Comment by frangio** [comment]
Yes, the rationale was to have the contracts be as simple as possible.

Since anyone can call the `release` functions in both timelock and vesting contracts, no changes are necessary to compose them with a SplitPayment kind of contract.

**Comment by elie222** [comment]
Thanks. The SplitPayment contract is for Ether rather than ERC20 tokens however. Would it make sense for us to add a ERC20SplitPayment type contract?
Is the preferred route? If we were to create a TokenVesting contract for multiple payees, would it be possible to add that to OpenZeppelin's suite of contracts, or due to it being slightly more complex, OZ will remain with only the simple single vestor contract?

**Comment by Shrugs** [comment]
A split ERC20 contract would be really nice; could it be included into `SplitPayment` itself?

**Comment by frangio** [comment]
I think we should add it to SplitPayment itself, yeah. I'm not sure what the interface would be. Maybe another set of functions which receive a token address.

As for adding a multiple-payee vesting contract,    I really think we should just keep the simple one.

**Comment by frangio** [comment]
I created #898 to fix this problem by composing with `SplitPayment`.
