### ISSUE TITLE
Your example

### ISSUE THREAD

**Issue by microdesign** [OpenZeppelin/zeppelin-solidity#861]
I using this example for my contract 

https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/examples/SampleCrowdsale.sol

I`m wrong or this way written the mint function revert because is not executed by the owner.

Upon a purchase I got revert error - when I delete onlyOwner on mint function of the token - everything is correct.

I use your latest code from GitHub

**Comment by Shrugs** [comment]
The crowdsale must be the owner of the mintable token if using a mintable token and mintable crowdsale. See the tests for an example: https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/test/crowdsale/MintedCrowdsale.test.js#L22

**Comment by microdesign** [comment]
So you mean after I deploy my contract I must run a transaction to actually own my own token ?

Also, how I`ll go to do this in a real network?

**Comment by Shrugs** [comment]
After you deploy your token contract, the deployer is the `owner`. Only the owner is allowed to mint tokens, so to use a `MintableCrowdsale`, the crowdsale must be the owner. You can change the owner of the token by doing `token.transferOwnership(crowdsaleAddress)`.

If you are using truffle to deploy, you can make this transaction part of your deploy script

**Comment by microdesign** [comment]
Is there any different to go with your way or create the token contract directly in my crowdsale contract?

**Comment by Shrugs** [comment]
The old version of OpenZeppelin's crowdsale created the token as part of the crowdsale, but there were a few issues with it, mainly inflexibility and the increased deployment size.

You can create a `Factory` contract that 
- deploys the token with your arguments
- deploys the crowdsale with your arguments
- transfers the ownership of the token to the crowdsale

all in one transaction if you'd like

**Comment by microdesign** [comment]
OK thanks for your help my problem is resolved
