### ISSUE TITLE
Failing Test

### ISSUE THREAD

**Issue by elie222** [OpenZeppelin/zeppelin-solidity#872]
When running the test suite, this test fails:

```
  1) Contract: Bounty Against broken contract claims reward:
     AssertionError: expected '1000000000000000000' to equal 2000000000000000000
      at _callee5$ (test/Bounty.test.js:96:16)
```

**Comment by frangio** [comment]
Hi @elie222, thanks for reporting. The test isn't failing in Travis CI and I can't reproduce the issue on my computer either.

Are you sure you're running the tests on an unmodified repo? Can you tell us more about your setup? Thanks!

**Comment by elie222** [comment]
I'm going to close this. Not sure how it could have happened. I ran the tests again now and all 743 pass. Not sure what happened that time. Not sure if it was truffle acting up...
