### ISSUE TITLE
ERC721 test is not checking name and symbol properly

### ISSUE THREAD

**Issue by vittominacori** [OpenZeppelin/zeppelin-solidity#910]
- [x] 🐛 This is a bug report.

## 📝 Details

On line 84 of ERC721Token.test.js (https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/test/token/ERC721/ERC721Token.test.js#L84) there is an error in assertion.

I think name is always equal to name if we check like below

`name.should.be.equal(name);`

Same for symbol.

**Comment by sebastien-kr** [comment]
To be honest there is no error in the assertion : 
`it('has a name', async function () {`

It only checks that there is a name, not that the name is the correct one. 
But it would be better to check that the name is the right one, I agree with you.
